# This file was generated by django-aqueduct.
# Run `dagger call regenerate-aqueduct-settings ...` to regenerate.
#
# Contains only settings specific to CMS and settings shared with the
# other service that have service-specific defaults.  The 486 settings
# identical across both services live in models/base.py so manual edits
# are not duplicated.

from __future__ import annotations

import datetime
from typing import Any

from pydantic import Field
from path import Path

from .base import SharedAqueductSettings


class AqueductSettings(SharedAqueductSettings):
    """Typed CMS Django settings model.

    Extends SharedAqueductSettings with CMS-specific fields and
    shared fields whose defaults differ between LMS and CMS.
    """

    ADVANCED_PROBLEM_TYPES: list[Any] = Field(
        default_factory=lambda: [
            {"component": "drag-and-drop-v2", "boilerplate_name": None},
            {"component": "staffgradedxblock", "boilerplate_name": None},
        ]
    )
    ALLOW_COURSE_RERUNS: bool = Field(default=True)
    ALLOW_UNICODE_COURSE_ID: bool = Field(default=False)
    ALTERNATE_WORKER_QUEUES: str = Field(default="lms")
    ANALYTICS_DASHBOARD_NAME: str = Field(default="Your Platform Name Here Insights")
    ANALYTICS_DASHBOARD_URL: str = Field(default="http://localhost:18110/courses")
    AUTHENTICATION_BACKENDS: list[Any] = Field(
        default_factory=lambda: [
            "auth_backends.backends.EdXOAuth2",
            "rules.permissions.ObjectPermissionBackend",
            "django.contrib.auth.backends.AllowAllUsersModelBackend",
            "bridgekeeper.backends.RulePermissionBackend",
        ]
    )
    AUTHORING_API_URL: str = Field(default="")
    AWS_SECURITY_TOKEN: Any = Field(default=None)  # TODO: refine type
    BRANCH_IO_KEY: str = Field(default="")
    CELERY_ALWAYS_EAGER: bool = Field(default=False)
    CELERY_DEFAULT_EXCHANGE: str = Field(default="edx.cms.core")
    CELERY_DEFAULT_QUEUE: str = Field(default="edx.cms.core.default")
    CELERY_DEFAULT_ROUTING_KEY: str = Field(default="edx.cms.core.default")
    CELERY_QUEUES: dict[str, Any] = Field(
        default_factory=lambda: {
            "edx.cms.core.high": {},
            "edx.cms.core.default": {},
            "edx.cms.core.low": {},
        }
    )
    CERT_QUEUE: str = Field(default="certificates")
    CLEAR_REQUEST_CACHE_ON_TASK_COMPLETION: bool = Field(default=True)
    CMS_BASE: Any = Field(default=None)  # TODO: refine type
    CMS_ROOT: str = Field(default=str(Path("/openedx/edx-platform/cms")))
    CMS_ROOT_URL: Any = Field(default=None)  # TODO: refine type
    CMS_SEGMENT_KEY: Any = Field(default=None)  # TODO: refine type
    CODE_JAIL: dict[str, Any] = Field(
        default_factory=lambda: {
            "python_bin": "/edx/app/edxapp/venvs/edxapp-sandbox/bin/python",
            "user": "sandbox",
            "limits": {
                "CPU": 1,
                "VMEM": 536870912,
                "REALTIME": 3,
                "PROXY": 0,
                "FSIZE": 1048576,
            },
            "limit_overrides": {},
        }
    )
    COMMENTS_SERVICE_KEY: str = Field(default="password")
    COMMENTS_SERVICE_URL: str = Field(default="http://localhost:18080")
    CONTACT_MAILING_ADDRESS: Any = Field(
        default=None
    )  # DERIVED: computed from other settings — add a @model_validator to reproduce
    CONTENTSTORE: dict[str, Any] = Field(
        default_factory=lambda: {
            "ENGINE": "xmodule.contentstore.mongo.MongoContentStore",
            "OPTIONS": {
                "db": "edxapp",
                "host": "localhost",
                "password": "password",
                "port": 27017,
                "user": "edxapp",
                "ssl": False,
                "auth_source": None,
            },
            "ADDITIONAL_OPTIONS": {},
            "DOC_STORE_CONFIG": {
                "db": "edxapp",
                "host": "localhost",
                "replicaSet": "",
                "port": 27017,
                "user": "edxapp",
                "collection": "modulestore",
                "ssl": False,
                "socketTimeoutMS": 6000,
                "connectTimeoutMS": 2000,
                "auth_source": None,
                "password": "password",
                "read_preference": "PRIMARY",
            },
        }
    )
    CORS_ALLOW_HEADERS: tuple[Any, ...] = Field(
        default=(
            "accept",
            "authorization",
            "content-type",
            "user-agent",
            "x-csrftoken",
            "x-requested-with",
            "use-jwt-cookie",
            "content-range",
            "content-disposition",
        )
    )  # TODO: refine type
    COURSE_EXPORT_DOWNLOAD_CHUNK_SIZE: int = Field(default=8192)
    COURSE_IMPORT_EXPORT_BUCKET: str = Field(default="")
    COURSE_IMPORT_EXPORT_STORAGE: str = Field(
        default="django.core.files.storage.FileSystemStorage"
    )
    COURSE_LIVE_HELP_URL: str = Field(
        default="https://docs.openedx.org/en/latest/educators/how-tos/course_development/add_course_live.html"
    )
    COURSE_METADATA_EXPORT_BUCKET: str = Field(default="")
    COURSE_METADATA_EXPORT_STORAGE: str = Field(
        default="django.core.files.storage.FileSystemStorage"
    )
    CREDENTIALS_INTERNAL_SERVICE_URL: str = Field(default="http://localhost:8005")
    CREDENTIALS_PUBLIC_SERVICE_URL: str = Field(default="http://localhost:8005")
    DATA_DIR: str = Field(default=str(Path("/openedx/data")))
    DEFAULT_COURSE_LANGUAGE: str = Field(default="en")
    DEFAULT_GRADE_DESIGNATIONS: list[Any] = Field(
        default_factory=lambda: ["A", "B", "C", "D"]
    )
    DEFAULT_ORG_LOGO_URL: str = Field(default="/static/studio/images/logo.png")
    DEFAULT_PRIORITY_QUEUE: str = Field(default="edx.cms.core.default")
    DEFAULT_TEMPLATE_ENGINE: dict[str, Any] = Field(
        default_factory=lambda: {
            "NAME": "django",
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "APP_DIRS": False,
            "DIRS": [
                Path("/openedx/edx-platform/cms/templates"),
                Path("/openedx/edx-platform/common/templates"),
                Path("/openedx/edx-platform/common/djangoapps/pipeline_mako/templates"),
                Path("/openedx/edx-platform/common/static"),
                Path(
                    "/openedx/edx-platform/openedx/core/djangoapps/cors_csrf/templates"
                ),
                Path(
                    "/openedx/edx-platform/openedx/core/djangoapps/dark_lang/templates"
                ),
                Path("/openedx/edx-platform/openedx/core/lib/license/templates"),
                Path("/openedx/edx-platform/cms/djangoapps/pipeline_js/templates"),
            ],
            "OPTIONS": {
                "loaders": [
                    "openedx.core.djangoapps.theming.template_loaders.ThemeTemplateLoader",
                    "common.djangoapps.edxmako.makoloader.MakoFilesystemLoader",
                    "common.djangoapps.edxmako.makoloader.MakoAppDirectoriesLoader",
                ],
                "context_processors": [
                    "django.template.context_processors.request",
                    "django.template.context_processors.static",
                    "django.template.context_processors.i18n",
                    "django.contrib.auth.context_processors.auth",
                    "django.template.context_processors.csrf",
                    "django.template.context_processors.media",
                    "django.template.context_processors.tz",
                    "django.contrib.messages.context_processors.messages",
                    "sekizai.context_processors.sekizai",
                    "common.djangoapps.edxmako.shortcuts.marketing_link_context_processor",
                    "lms.djangoapps.courseware.context_processor.user_timezone_locale_prefs",
                    "help_tokens.context_processor",
                    "openedx.core.djangoapps.site_configuration.context_processors.configuration_context",
                    "lms.djangoapps.mobile_api.context_processor.is_from_mobile_app",
                    "openedx.features.survey_report.context_processors.admin_extra_context",
                    "social_django.context_processors.backends",
                    "social_django.context_processors.login_redirect",
                ],
                "debug": False,
            },
        }
    )
    DEPRECATE_OLD_COURSE_KEYS_IN_STUDIO: bool = Field(default=True)
    DISABLE_ADVANCED_SETTINGS: bool = Field(default=False)
    DISABLE_COURSE_CREATION: bool = Field(default=False)
    DISABLE_DEPRECATED_SIGNIN_URL: bool = Field(default=False)
    DISABLE_DEPRECATED_SIGNUP_URL: bool = Field(default=False)
    DISCUSSIONS_INCONTEXT_FEEDBACK_URL: str = Field(default="")
    DISCUSSIONS_INCONTEXT_LEARNMORE_URL: str = Field(
        default="https://docs.openedx.org/en/latest/educators/concepts/communication/about_course_discussions.html"
    )
    DOC_STORE_CONFIG: dict[str, Any] = Field(
        default_factory=lambda: {
            "db": "edxapp",
            "host": "localhost",
            "replicaSet": "",
            "port": 27017,
            "user": "edxapp",
            "collection": "modulestore",
            "ssl": False,
            "socketTimeoutMS": 6000,
            "connectTimeoutMS": 2000,
            "auth_source": None,
            "password": "password",
            "read_preference": "PRIMARY",
        }
    )
    EDITABLE_SHORT_DESCRIPTION: bool = Field(default=True)
    EDXAPP_PARSE_KEYS: dict[str, Any] = Field(default_factory=lambda: {})
    ELASTIC_FIELD_MAPPINGS: dict[str, Any] = Field(
        default_factory=lambda: {"start_date": {"type": "date"}}
    )
    EMAIL_FILE_PATH: str = Field(default=str(Path("/openedx/data/emails/studio")))
    ENABLE_AUTO_GITHUB_REPO_CREATION: bool = Field(default=False)
    ENABLE_CONTENT_LIBRARIES: bool = Field(default=True)
    ENABLE_COUNTRY_ACCESS: bool = Field(default=False)
    ENABLE_COURSEWARE_INDEX: bool = Field(default=False)
    ENABLE_CREATOR_GROUP: bool = Field(default=True)
    ENABLE_CREDIT_API: bool = Field(default=False)
    ENABLE_DATES_COURSE_APP: bool = Field(default=False)
    ENABLE_DISCUSSION_HOME_PANEL: bool = Field(default=True)
    ENABLE_GIT_AUTO_EXPORT: bool = Field(default=True)
    ENABLE_GRADE_DOWNLOADS: bool = Field(default=True)
    ENABLE_HIDE_FROM_TOC_UI: bool = Field(default=False)
    ENABLE_LIBRARY_INDEX: bool = Field(default=False)
    ENABLE_MAX_FAILED_LOGIN_ATTEMPTS: bool = Field(default=False)
    ENABLE_ORGANIZATION_STAFF_ACCESS_FOR_CONTENT_LIBRARIES: bool = Field(default=True)
    ENABLE_OTHER_COURSE_SETTINGS: bool = Field(default=False)
    ENABLE_RAPID_RESPONSE_AUTHOR_VIEW: bool = Field(default=False)
    ENABLE_SEND_XBLOCK_LIFECYCLE_EVENTS_OVER_BUS: bool = Field(default=False)
    ENABLE_SEPARATE_ARCHIVED_COURSES: bool = Field(default=True)
    ENABLE_VIDEO_UPLOAD_PIPELINE: bool = Field(default=False)
    ENTERPRISE_API_URL: str = Field(default="http://localhost:18000/enterprise/api/v1/")
    ENTERPRISE_CONSENT_API_URL: str = Field(
        default="http://localhost:18000/consent/api/v1/"
    )
    ENTERPRISE_ENROLLMENT_API_URL: str = Field(
        default="http://localhost:18000/api/enrollment/v1/"
    )
    ENTRANCE_EXAMS: bool = Field(default=False)
    EVENT_BUS_PRODUCER_CONFIG: dict[str, Any] = Field(
        default_factory=lambda: {
            "org.openedx.learning.course.passing.status.updated.v1": {
                "learning-badges-lifecycle": {
                    "event_key_field": "course_passing_status.course.course_key",
                    "enabled": False,
                }
            },
            "org.openedx.learning.ccx.course.passing.status.updated.v1": {
                "learning-badges-lifecycle": {
                    "event_key_field": "course_passing_status.course.ccx_course_key",
                    "enabled": False,
                }
            },
            "org.openedx.learning.certificate.created.v1": {
                "learning-certificate-lifecycle": {
                    "event_key_field": "certificate.course.course_key",
                    "enabled": False,
                }
            },
            "org.openedx.learning.certificate.revoked.v1": {
                "learning-certificate-lifecycle": {
                    "event_key_field": "certificate.course.course_key",
                    "enabled": False,
                }
            },
            "org.openedx.learning.course.unenrollment.completed.v1": {
                "course-unenrollment-lifecycle": {
                    "event_key_field": "enrollment.course.course_key",
                    "enabled": False,
                }
            },
            "org.openedx.learning.xblock.skill.verified.v1": {
                "learning-xblock-skill-verified": {
                    "event_key_field": "xblock_info.usage_key",
                    "enabled": False,
                }
            },
            "org.openedx.learning.user.course_access_role.added.v1": {
                "learning-course-access-role-lifecycle": {
                    "event_key_field": "course_access_role_data.course_key",
                    "enabled": False,
                }
            },
            "org.openedx.learning.user.course_access_role.removed.v1": {
                "learning-course-access-role-lifecycle": {
                    "event_key_field": "course_access_role_data.course_key",
                    "enabled": False,
                }
            },
            "org.openedx.enterprise.learner_credit_course_enrollment.revoked.v1": {
                "learner-credit-course-enrollment-lifecycle": {
                    "event_key_field": "learner_credit_course_enrollment.uuid",
                    "enabled": False,
                }
            },
            "org.openedx.learning.external_grader.score.submitted.v1": {
                "learning-external-grader-score-lifecycle": {
                    "event_key_field": "score.submission_id",
                    "enabled": False,
                }
            },
            "org.openedx.content_authoring.course.catalog_info.changed.v1": {
                "course-catalog-info-changed": {
                    "event_key_field": "catalog_info.course_key",
                    "enabled": False,
                }
            },
            "org.openedx.content_authoring.xblock.published.v1": {
                "course-authoring-xblock-lifecycle": {
                    "event_key_field": "xblock_info.usage_key",
                    "enabled": False,
                }
            },
            "org.openedx.content_authoring.xblock.deleted.v1": {
                "course-authoring-xblock-lifecycle": {
                    "event_key_field": "xblock_info.usage_key",
                    "enabled": False,
                }
            },
            "org.openedx.content_authoring.xblock.duplicated.v1": {
                "course-authoring-xblock-lifecycle": {
                    "event_key_field": "xblock_info.usage_key",
                    "enabled": False,
                }
            },
        }
    )
    EXAMS_SERVICE_USERNAME: str = Field(default="edx_exams_worker")
    EXTENDED_VIDEO_TRANSCRIPT_LANGUAGES: list[Any] = Field(default_factory=lambda: [])
    EXTRA_MIDDLEWARE_CLASSES: list[Any] = Field(default_factory=lambda: [])
    FACEBOOK_API_VERSION: str = Field(default="v2.1")
    FACEBOOK_APP_ID: str = Field(default="FACEBOOK_APP_ID")
    FACEBOOK_APP_SECRET: str = Field(default="FACEBOOK_APP_SECRET")
    FILES_AND_UPLOAD_TYPE_FILTERS: dict[str, Any] = Field(
        default_factory=lambda: {
            "Images": [
                "image/png",
                "image/jpeg",
                "image/jpg",
                "image/gif",
                "image/tiff",
                "image/tif",
                "image/x-icon",
                "image/svg+xml",
                "image/bmp",
                "image/x-ms-bmp",
            ],
            "Documents": [
                "application/pdf",
                "text/plain",
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
                "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
                "application/vnd.openxmlformats-officedocument.presentationml.template",
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
                "application/msword",
                "application/vnd.ms-excel",
                "application/vnd.ms-powerpoint",
                "application/csv",
                "application/vnd.ms-excel.sheet.macroEnabled.12",
                "text/x-tex",
                "application/x-pdf",
                "application/vnd.ms-excel.sheet.macroenabled.12",
                "file/pdf",
                "image/pdf",
                "text/csv",
                "text/pdf",
                "text/x-sh",
                '"application/pdf"',
            ],
            "Audio": [
                "audio/mpeg",
                "audio/mp3",
                "audio/x-wav",
                "audio/ogg",
                "audio/wav",
                "audio/aac",
                "audio/x-m4a",
                "audio/mp4",
                "audio/x-ms-wma",
            ],
            "Code": [
                "application/json",
                "text/html",
                "text/javascript",
                "application/javascript",
                "text/css",
                "text/x-python",
                "application/x-java-jnlp-file",
                "application/xml",
                "application/postscript",
                "application/x-javascript",
                "application/java-vm",
                "text/x-c++src",
                "text/xml",
                "text/x-scss",
                "application/x-python-code",
                "application/java-archive",
                "text/x-python-script",
                "application/x-ruby",
                "application/mathematica",
                "text/coffeescript",
                "text/x-matlab",
                "application/sql",
                "text/php",
            ],
        }
    )
    FRONTEND_LOGIN_URL: str = Field(default="/login/")
    FRONTEND_LOGOUT_URL: str = Field(default="/logout/")
    FRONTEND_REGISTER_URL: str = Field(default="http://localhost:18000/register")
    GITHUB_ACCESS_TOKEN: Any = Field(default=None)  # TODO: refine type
    GITHUB_ORG_API_URL: str = Field(default="")
    GITHUB_PUSH: bool = Field(default=False)
    GITHUB_REPO_ROOT: str = Field(default=str(Path("/openedx/data")))
    GIT_EXPORT_DEFAULT_IDENT: dict[str, Any] = Field(
        default_factory=lambda: {
            "name": "STUDIO_EXPORT_TO_GIT",
            "email": "STUDIO_EXPORT_TO_GIT@example.com",
        }
    )
    GIT_REPO_EXPORT_DIR: str = Field(default="/openedx/export_course_repos")
    HEARTBEAT_CELERY_ROUTING_KEY: str = Field(default="edx.cms.core.high")
    HELP_TOKENS_INI_FILE: str = Field(
        default=str(Path("/openedx/edx-platform/cms/envs/help_tokens.ini"))
    )
    HIGH_PRIORITY_QUEUE: str = Field(default="edx.cms.core.high")
    HOTJAR_ID: int = Field(default=0)
    INACTIVE_USER_LOGIN: bool = Field(default=True)
    INACTIVE_USER_URL: str = Field(default="http://None")
    INSTALLED_APPS: list[Any] = Field(
        default_factory=lambda: [
            "django.contrib.auth",
            "django.contrib.contenttypes",
            "django.contrib.humanize",
            "django.contrib.redirects",
            "django.contrib.sessions",
            "django.contrib.sites",
            "django.contrib.messages",
            "openedx.core.djangoapps.staticfiles.apps.EdxPlatformStaticFilesConfig",
            "django_celery_results",
            "method_override",
            "openedx.core.djangoapps.common_initialization.apps.CommonInitializationConfig",
            "openedx.core.djangoapps.common_views",
            "openedx.core.djangoapps.api_admin",
            "corsheaders",
            "openedx.core.djangoapps.cors_csrf",
            "xss_utils",
            "simple_history",
            "config_models",
            "openedx.core.djangoapps.config_model_utils",
            "waffle",
            "openedx.core.djangoapps.service_status",
            "openedx.core.djangoapps.video_config",
            "openedx.core.djangoapps.video_pipeline",
            "cms.djangoapps.contentstore.apps.ContentstoreConfig",
            "common.djangoapps.split_modulestore_django.apps.SplitModulestoreDjangoBackendAppConfig",
            "openedx.core.djangoapps.contentserver",
            "cms.djangoapps.course_creators",
            "common.djangoapps.student.apps.StudentConfig",
            "openedx.core.djangoapps.course_groups",
            "cms.djangoapps.xblock_config.apps.XBlockConfig",
            "cms.djangoapps.export_course_metadata.apps.ExportCourseMetadataConfig",
            "cms.djangoapps.modulestore_migrator",
            "openedx.core.djangoapps.xblock.apps.StudioXBlockAppConfig",
            "openedx.core.djangoapps.util.apps.UtilConfig",
            "common.djangoapps.track",
            "eventtracking.django.apps.EventTrackingConfig",
            "common.djangoapps.edxmako.apps.EdxMakoConfig",
            "pipeline",
            "common.djangoapps.static_replace",
            "require",
            "webpack_loader",
            "openedx.core.djangoapps.site_configuration",
            "openedx.core.djangoapps.crawlers",
            "openedx.core.djangoapps.django_comment_common",
            "openedx.core.djangoapps.notifications",
            "django.contrib.admin",
            "common.djangoapps.course_modes.apps.CourseModesConfig",
            "openedx.core.djangoapps.verified_track_content",
            "openedx.core.djangoapps.dark_lang",
            "wiki",
            "django_notify",
            "lms.djangoapps.course_wiki",
            "mptt",
            "sekizai",
            "openedx.core.djangoapps.user_api",
            "openedx.core.djangoapps.embargo",
            "common.djangoapps.course_action_state",
            "submissions",
            "openassessment",
            "openassessment.assessment",
            "openassessment.fileupload",
            "openassessment.staffgrader",
            "openassessment.workflow",
            "openassessment.xblock",
            "edxval",
            "openedx.core.djangoapps.content.course_overviews.apps.CourseOverviewsConfig",
            "openedx.core.djangoapps.content.block_structure.apps.BlockStructureConfig",
            "milestones",
            "openedx.core.djangoapps.credit.apps.CreditConfig",
            "common.djangoapps.xblock_django",
            "openedx.core.djangoapps.agreements",
            "openedx.core.djangoapps.catalog",
            "openedx.core.djangoapps.programs.apps.ProgramsConfig",
            "oauth2_provider",
            "openedx.core.djangoapps.oauth_dispatch.apps.OAuthDispatchAppConfig",
            "lms.djangoapps.courseware",
            "lms.djangoapps.coursewarehistoryextended",
            "lms.djangoapps.survey.apps.SurveyConfig",
            "lms.djangoapps.verify_student.apps.VerifyStudentConfig",
            "completion",
            "openedx.core.djangoapps.system_wide_roles",
            "statici18n",
            "cms.lib.xblock.tagging",
            "django_sites_extensions",
            "release_util",
            "rules.apps.AutodiscoverRulesConfig",
            "bridgekeeper",
            "user_tasks",
            "cms.djangoapps.cms_user_tasks.apps.CmsUserTasksConfig",
            "common.djangoapps.database_fixups",
            "celery_utils",
            "openedx.core.djangoapps.waffle_utils",
            "django_filters",
            "cms.djangoapps.api",
            "csrf.apps.CsrfAppConfig",
            "common.djangoapps.entitlements",
            "common.djangoapps.pipeline_mako",
            "drf_yasg",
            "openedx_tagging",
            "openedx.core.djangoapps.content_tagging",
            "openedx.core.djangoapps.content.search",
            "lms.djangoapps.program_enrollments",
            "openedx.features.course_duration_limits",
            "openedx.features.content_type_gating",
            "openedx.features.discounts",
            "openedx.features.effort_estimation",
            "lms.djangoapps.experiments",
            "openedx.core.djangoapps.external_user_ids",
            "openedx.core.djangoapps.heartbeat",
            "openedx.core.djangoapps.course_date_signals",
            "openedx.core.djangoapps.schedules",
            "rest_framework_jwt",
            "openedx.core.djangoapps.content.learning_sequences.apps.LearningSequencesConfig",
            "organizations",
            "edx_django_utils.user",
            "social_django",
            "pylti1p3.contrib.django.lti1p3_tool_config",
            "edx_ace",
            "drf_spectacular",
            "openedx.core.djangoapps.authz",
            "openedx_events",
            "openedx_catalog",
            "openedx_content",
            "openedx_content.backcompat.backup_restore",
            "openedx_content.backcompat.collections",
            "openedx_content.backcompat.components",
            "openedx_content.backcompat.contents",
            "openedx_content.backcompat.publishing",
            "openedx_content.backcompat.sections",
            "openedx_content.backcompat.subsections",
            "openedx_content.backcompat.units",
            "edx_sga",
            "integrated_channels.integrated_channel",
            "integrated_channels.degreed",
            "integrated_channels.degreed2",
            "integrated_channels.sap_success_factors",
            "integrated_channels.cornerstone",
            "integrated_channels.xapi",
            "integrated_channels.blackboard",
            "integrated_channels.canvas",
            "integrated_channels.moodle",
            "channel_integrations.integrated_channel",
            "channel_integrations.degreed2",
            "channel_integrations.sap_success_factors",
            "channel_integrations.cornerstone",
            "channel_integrations.xapi",
            "channel_integrations.blackboard",
            "channel_integrations.canvas",
            "channel_integrations.moodle",
            "django_object_actions",
            "openedx.core.djangoapps.ace_common.apps.AceCommonConfig",
            "openedx.core.djangoapps.bookmarks.apps.BookmarksConfig",
            "openedx.core.djangoapps.content_libraries.apps.ContentLibrariesConfig",
            "openedx.core.djangoapps.content_staging.apps.ContentStagingAppConfig",
            "openedx.core.djangoapps.course_apps.apps.CourseAppsConfig",
            "openedx.core.djangoapps.course_live.apps.CourseLiveConfig",
            "lms.djangoapps.discussion.apps.DiscussionConfig",
            "openedx.core.djangoapps.discussions.apps.DiscussionsConfig",
            "lms.djangoapps.instructor.apps.InstructorConfig",
            "openedx.core.djangoapps.olx_rest_api.apps.OlxRestApiAppConfig",
            "openedx.core.djangoapps.password_policy.apps.PasswordPolicyConfig",
            "openedx.core.djangoapps.plugins.apps.PluginsConfig",
            "openedx.core.djangoapps.theming.apps.ThemingConfig",
            "openedx.core.djangoapps.user_authn.apps.UserAuthnConfig",
            "openedx.core.djangoapps.zendesk_proxy.apps.ZendeskProxyConfig",
            "ol_openedx_auto_select_language.apps.OLOpenEdxAutoSelectLanguageConfig",
            "ol_openedx_course_translations.apps.OLOpenedXCourseTranslationsConfig",
            "ol_openedx_ai_static_translations.apps.OLOpenedXAIStaticTranslationsConfig",
            "ol_openedx_chat.apps.OLOpenedxChatConfig",
            "edx_when.apps.EdxWhenConfig",
            "ol_openedx_canvas_integration.app.CanvasIntegrationConfig",
            "ol_openedx_git_auto_export.app.GitAutoExportConfig",
            "edx_username_changer.apps.EdxUsernameChangerConfig",
            "ol_openedx_chat_xblock.apps.OLOpenedxChatXBlockConfig",
            "ol_openedx_uai_content_customization.apps.OLOpenEdxUaiContentCustomizationConfig",
            "openedx_authz.apps.OpenedxAuthzConfig",
            "ol_openedx_course_sync.apps.OLOpenEdxCourseSyncConfig",
            "lti_consumer.apps.LTIConsumerApp",
            "ol_openedx_events_handler.apps.OlOpenedxEventsHandlerConfig",
            "edx_proctoring.apps.EdxProctoringConfig",
            "ol_openedx_sentry.app.EdxSentry",
            "ol_openedx_logging.app.EdxLoggingCMS",
            "consent.apps.ConsentConfig",
            "enterprise.apps.EnterpriseConfig",
            "ol_openedx_course_export.app.CourseExportConfig",
            "rapid_response_xblock.apps.RapidResponseAppConfig",
            "edx_sysadmin.apps.EdxSysAdminConfig",
            "push_notifications",
            "openedx_authz.engine.apps.CasbinAdapterConfig",
        ]
    )
    IN_CONTEXT_DISCUSSION_ENABLED_DEFAULT: bool = Field(default=True)
    LEARNER_PORTAL_URL_ROOT: str = Field(
        default="https://learner-portal-localhost:18000"
    )
    LIBRARY_BLOCK_TYPES: list[Any] = Field(
        default_factory=lambda: [
            {"component": "library_content", "boilerplate_name": None}
        ]
    )
    LIBRARY_ENABLED_BLOCKS: list[Any] = Field(
        default_factory=lambda: [
            "problem",
            "video",
            "html",
            "drag-and-drop-v2",
            "openassessment",
            "conditional",
            "done",
            "edx_sga",
            "freetextresponse",
            "google-calendar",
            "google-document",
            "invideoquiz",
            "lti",
            "lti_consumer",
            "pdf",
            "poll",
            "survey",
            "word_cloud",
        ]
    )
    LMS_BASE: Any = Field(default=None)  # TODO: refine type
    LMS_INTERNAL_ROOT_URL: str = Field(default="http://localhost:18000")
    LMS_ROOT: str = Field(default=str(Path("/openedx/edx-platform/lms")))
    LMS_ROOT_URL: str = Field(default="http://localhost:18000")
    LOGIN_REDIRECT_URL: str = Field(default="/home/")
    LOGIN_URL: str = Field(default="/login/")
    LOW_PRIORITY_QUEUE: str = Field(default="edx.cms.core.low")
    MAINTENANCE_BANNER_TEXT: str = Field(default="Sample banner message")
    MAKO_MODULE_DIR: str = Field(default="/tmp/mako_cms")
    MAKO_TEMPLATE_DIRS_BASE: list[Any] = Field(
        default_factory=lambda: [
            Path("/openedx/edx-platform/cms/templates"),
            Path("/openedx/edx-platform/common/templates"),
            Path("/openedx/edx-platform/common/djangoapps/pipeline_mako/templates"),
            Path("/openedx/edx-platform/common/static"),
            Path("/openedx/edx-platform/openedx/core/djangoapps/cors_csrf/templates"),
            Path("/openedx/edx-platform/openedx/core/djangoapps/dark_lang/templates"),
            Path("/openedx/edx-platform/openedx/core/lib/license/templates"),
            Path("/openedx/edx-platform/cms/djangoapps/pipeline_js/templates"),
        ]
    )
    MAX_ASSET_UPLOAD_FILE_SIZE_IN_MB: int = Field(default=20)
    MAX_ASSET_UPLOAD_FILE_SIZE_URL: str = Field(default="")
    MAX_BLOCKS_PER_CONTENT_LIBRARY: int = Field(default=100000)
    MEILISEARCH_API_KEY: str = Field(default="devkey")
    MEILISEARCH_ENABLED: bool = Field(default=False)
    MEILISEARCH_INDEX_PREFIX: str = Field(default="")
    MEILISEARCH_PUBLIC_URL: str = Field(default="http://meilisearch.example.com")
    MEILISEARCH_URL: str = Field(default="http://meilisearch")
    MIDDLEWARE: list[Any] = Field(
        default_factory=lambda: [
            "openedx.core.lib.x_forwarded_for.middleware.XForwardedForMiddleware",
            "edx_django_utils.security.csp.middleware.content_security_policy_middleware",
            "crum.CurrentRequestUserMiddleware",
            "edx_django_utils.cache.middleware.RequestCacheMiddleware",
            "edx_django_utils.monitoring.CookieMonitoringMiddleware",
            "edx_django_utils.monitoring.DeploymentMonitoringMiddleware",
            "edx_django_utils.monitoring.FrontendMonitoringMiddleware",
            "edx_django_utils.monitoring.MonitoringMemoryMiddleware",
            "openedx.core.djangoapps.header_control.middleware.HeaderControlMiddleware",
            "django.middleware.cache.UpdateCacheMiddleware",
            "django.middleware.common.CommonMiddleware",
            "django.contrib.sites.middleware.CurrentSiteMiddleware",
            "django.middleware.csrf.CsrfViewMiddleware",
            "corsheaders.middleware.CorsMiddleware",
            "openedx.core.djangoapps.cors_csrf.middleware.CorsCSRFMiddleware",
            "openedx.core.djangoapps.cors_csrf.middleware.CsrfCrossDomainCookieMiddleware",
            "edx_rest_framework_extensions.auth.jwt.middleware.JwtAuthCookieMiddleware",
            "django_sites_extensions.middleware.RedirectMiddleware",
            "openedx.core.djangoapps.safe_sessions.middleware.SafeSessionMiddleware",
            "method_override.middleware.MethodOverrideMiddleware",
            "openedx.core.djangoapps.cache_toolbox.middleware.CacheBackedAuthenticationMiddleware",
            "common.djangoapps.student.middleware.UserStandingMiddleware",
            "django.contrib.messages.middleware.MessageMiddleware",
            "common.djangoapps.track.middleware.TrackMiddleware",
            "openedx.core.djangoapps.lang_pref.middleware.LanguagePreferenceMiddleware",
            "openedx.core.djangoapps.dark_lang.middleware.DarkLangMiddleware",
            "openedx.core.djangoapps.embargo.middleware.EmbargoMiddleware",
            "django.middleware.locale.LocaleMiddleware",
            "codejail.django_integration.ConfigureCodeJailMiddleware",
            "openedx.core.djangoapps.session_inactivity_timeout.middleware.SessionInactivityTimeout",
            "openedx.core.djangoapps.theming.middleware.CurrentSiteThemeMiddleware",
            "django.middleware.clickjacking.XFrameOptionsMiddleware",
            "waffle.middleware.WaffleMiddleware",
            "edx_django_utils.cache.middleware.TieredCacheMiddleware",
            "edx_rest_framework_extensions.middleware.RequestCustomAttributesMiddleware",
            "edx_rest_framework_extensions.auth.jwt.middleware.EnsureJWTAuthSettingsMiddleware",
            "simple_history.middleware.HistoryRequestMiddleware",
            "openedx.core.djangoapps.site_configuration.middleware.SessionCookieDomainOverrideMiddleware",
            "ol_openedx_auto_select_language.middleware.CourseLanguageCookieResetMiddleware",
        ]
    )
    MODULESTORE: dict[str, Any] = Field(
        default_factory=lambda: {
            "default": {
                "ENGINE": "xmodule.modulestore.mixed.MixedModuleStore",
                "OPTIONS": {
                    "mappings": {},
                    "stores": [
                        {
                            "NAME": "split",
                            "ENGINE": "xmodule.modulestore.split_mongo.split_draft.DraftVersioningModuleStore",
                            "DOC_STORE_CONFIG": {
                                "db": "edxapp",
                                "host": "localhost",
                                "replicaSet": "",
                                "port": 27017,
                                "user": "edxapp",
                                "collection": "modulestore",
                                "ssl": False,
                                "socketTimeoutMS": 6000,
                                "connectTimeoutMS": 2000,
                                "auth_source": None,
                                "password": "password",
                                "read_preference": "PRIMARY",
                            },
                            "OPTIONS": {
                                "default_class": "xmodule.hidden_block.HiddenBlock",
                                "fs_root": "/edx/var/edxapp/data",
                                "render_template": "common.djangoapps.edxmako.shortcuts.render_to_string",
                            },
                        },
                        {
                            "NAME": "draft",
                            "ENGINE": "xmodule.modulestore.mongo.DraftMongoModuleStore",
                            "DOC_STORE_CONFIG": {
                                "db": "edxapp",
                                "host": "localhost",
                                "replicaSet": "",
                                "port": 27017,
                                "user": "edxapp",
                                "collection": "modulestore",
                                "ssl": False,
                                "socketTimeoutMS": 6000,
                                "connectTimeoutMS": 2000,
                                "auth_source": None,
                                "password": "password",
                                "read_preference": "PRIMARY",
                            },
                            "OPTIONS": {
                                "default_class": "xmodule.hidden_block.HiddenBlock",
                                "fs_root": "/edx/var/edxapp/data",
                                "render_template": "common.djangoapps.edxmako.shortcuts.render_to_string",
                            },
                        },
                    ],
                },
            }
        }
    )
    MODULESTORE_BRANCH: str = Field(default="draft-preferred")
    MODULESTORE_FIELD_OVERRIDE_PROVIDERS: tuple[Any, ...] = Field(
        default=()
    )  # TODO: refine type
    OAUTH_ID_TOKEN_EXPIRATION: int = Field(default=300)
    ORA2_FILE_PREFIX: str = Field(default="default_env-default_deployment/ora2")
    ORGANIZATIONS_AUTOCREATE: bool = Field(default=True)
    PARSE_KEYS: dict[str, Any] = Field(default_factory=lambda: {})
    PIPELINE: dict[str, Any] = Field(
        default_factory=lambda: {
            "PIPELINE_ENABLED": True,
            "CSS_COMPRESSOR": None,
            "DISABLE_WRAPPER": True,
            "UGLIFYJS_BINARY": "node_modules/.bin/uglifyjs",
            "JS_COMPRESSOR": None,
            "STYLESHEETS": {
                "style-vendor": {
                    "source_filenames": [
                        "css/vendor/normalize.css",
                        "css/vendor/font-awesome.css",
                        "css/vendor/html5-input-polyfills/number-polyfill.css",
                        "js/vendor/CodeMirror/codemirror.css",
                        "css/vendor/ui-lightness/jquery-ui-1.8.22.custom.css",
                        "css/vendor/jquery.qtip.min.css",
                        "js/vendor/markitup/skins/simple/style.css",
                        "js/vendor/markitup/sets/wiki/style.css",
                    ],
                    "output_filename": "css/cms-style-vendor.css",
                },
                "style-vendor-tinymce-content": {
                    "source_filenames": [
                        "css/tinymce-studio-content-fonts.css",
                        "js/vendor/tinymce/js/tinymce/skins/ui/studio-tmce5/content.min.css",
                        "css/tinymce-studio-content.css",
                    ],
                    "output_filename": "css/cms-style-vendor-tinymce-content.css",
                },
                "style-vendor-tinymce-skin": {
                    "source_filenames": [
                        "js/vendor/tinymce/js/tinymce/skins/ui/studio-tmce5/skin.min.css"
                    ],
                    "output_filename": "css/cms-style-vendor-tinymce-skin.css",
                },
                "style-main-v1": {
                    "source_filenames": ["css/studio-main-v1.css"],
                    "output_filename": "css/studio-main-v1.css",
                },
                "style-main-v1-rtl": {
                    "source_filenames": ["css/studio-main-v1-rtl.css"],
                    "output_filename": "css/studio-main-v1-rtl.css",
                },
                "style-xmodule-annotations": {
                    "source_filenames": [
                        "css/vendor/ova/annotator.css",
                        "css/vendor/ova/edx-annotator.css",
                        "css/vendor/ova/video-js.min.css",
                        "css/vendor/ova/rangeslider.css",
                        "css/vendor/ova/share-annotator.css",
                        "css/vendor/ova/richText-annotator.css",
                        "css/vendor/ova/tags-annotator.css",
                        "css/vendor/ova/flagging-annotator.css",
                        "css/vendor/ova/diacritic-annotator.css",
                        "css/vendor/ova/grouping-annotator.css",
                        "css/vendor/ova/ova.css",
                        "js/vendor/ova/catch/css/main.css",
                    ],
                    "output_filename": "css/cms-style-xmodule-annotations.css",
                },
                "course-unit-mfe-iframe-bundle": {
                    "source_filenames": ["css/course-unit-mfe-iframe-bundle.css"],
                    "output_filename": "css/course-unit-mfe-iframe-bundle.css",
                },
            },
            "JAVASCRIPT": {
                "base_vendor": {
                    "source_filenames": [
                        "js/src/utility.js",
                        "js/src/logger.js",
                        "common/js/vendor/jquery.js",
                        "common/js/vendor/jquery-migrate.js",
                        "js/vendor/jquery.cookie.js",
                        "js/vendor/url.min.js",
                        "common/js/vendor/underscore.js",
                        "common/js/vendor/underscore.string.js",
                        "common/js/vendor/backbone.js",
                        "js/vendor/URI.min.js",
                        "edx-ui-toolkit/js/utils/global-loader.js",
                        "edx-ui-toolkit/js/utils/string-utils.js",
                        "edx-ui-toolkit/js/utils/html-utils.js",
                        "common/js/vendor/require.js",
                    ],
                    "output_filename": "js/cms-base-vendor.js",
                },
                "proctoring": {
                    "source_filenames": [
                        "proctoring/js/models/proctored_exam_allowance_model.js",
                        "proctoring/js/models/proctored_exam_attempt_model.js",
                        "proctoring/js/models/proctored_exam_bulk_allowance_model.js",
                        "proctoring/js/models/proctored_exam_model.js",
                        "proctoring/js/models/learner_onboarding_model.js",
                        "proctoring/js/collections/proctored_exam_allowance_collection.js",
                        "proctoring/js/collections/proctored_exam_attempt_grouped_collection.js",
                        "proctoring/js/collections/proctored_exam_onboarding_collection.js",
                        "proctoring/js/collections/proctored_exam_collection.js",
                        "proctoring/js/views/Backbone.ModalDialog.js",
                        "proctoring/js/views/proctored_exam_add_allowance_view.js",
                        "proctoring/js/views/proctored_exam_add_bulk_allowance_view.js",
                        "proctoring/js/views/proctored_exam_allowance_view.js",
                        "proctoring/js/views/proctored_exam_attempt_view.js",
                        "proctoring/js/views/proctored_exam_edit_allowance_view.js",
                        "proctoring/js/views/proctored_exam_onboarding_view.js",
                        "proctoring/js/views/proctored_exam_view.js",
                        "proctoring/js/views/proctored_exam_info.js",
                        "proctoring/js/views/proctored_exam_instructor_launch.js",
                        "proctoring/js/proctored_app.js",
                        "proctoring/js/exam_action_handler.js",
                        "proctoring/js/dropdown.js",
                    ],
                    "output_filename": "js/lms-proctoring.js",
                },
            },
            "COMPILERS": (),
            "YUI_BINARY": "yui-compressor",
        }
    )
    POLICY_CHANGE_GRADES_ROUTING_KEY: str = Field(default="edx.cms.core.default")
    PREVENT_CONCURRENT_LOGINS: bool = Field(default=False)
    PROJECT_ROOT: str = Field(default=str(Path("/openedx/edx-platform/cms")))
    RECALCULATE_GRADES_ROUTING_KEY: str = Field(default="edx.cms.core.default")
    REGISTRATION_EXTRA_FIELDS: dict[str, Any] = Field(
        default_factory=lambda: {
            "confirm_email": "hidden",
            "level_of_education": "optional",
            "gender": "optional",
            "year_of_birth": "optional",
            "mailing_address": "optional",
            "goals": "optional",
            "honor_code": "required",
            "terms_of_service": "hidden",
            "city": "hidden",
            "country": "hidden",
            "marketing_emails_opt_in": "hidden",
        }
    )
    REQUIRE_BUILD_PROFILE: str = Field(default="cms/js/build.js")
    REQUIRE_JS: str = Field(default="js/vendor/requiresjs/require.js")
    REST_FRAMEWORK: dict[str, Any] = Field(
        default_factory=lambda: {
            "DEFAULT_AUTHENTICATION_CLASSES": [
                "openedx.core.djangolib.default_auth_classes.DefaultJwtAuthentication",
                "openedx.core.djangolib.default_auth_classes.DefaultSessionAuthentication",
            ],
            "DEFAULT_PAGINATION_CLASS": "edx_rest_framework_extensions.paginators.DefaultPagination",
            "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
            "EXCEPTION_HANDLER": "openedx.core.lib.request_utils.ignored_error_exception_handler",
            "PAGE_SIZE": 10,
            "URL_FORMAT_OVERRIDE": None,
            "DEFAULT_THROTTLE_RATES": {
                "user": "60/minute",
                "service_user": "800/minute",
                "registration_validation": "30/minute",
                "high_service_user": "2000/minute",
            },
            "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
        }
    )
    ROOT_URLCONF: str = Field(default="cms.urls")
    SCRAPE_YOUTUBE_THUMBNAILS_JOB_QUEUE: str = Field(default="edx.cms.core.default")
    SERVICE_VARIANT: str = Field(default="cms")
    SINGLE_LEARNER_COURSE_REGRADE_ROUTING_KEY: str = Field(
        default="edx.cms.core.default"
    )
    SOCIAL_AUTH_STRATEGY: str = Field(
        default="auth_backends.strategies.EdxDjangoStrategy"
    )
    SOFTWARE_SECURE_VERIFICATION_ROUTING_KEY: str = Field(default="edx.cms.core.high")
    SQUELCH_PII_IN_LOGS: bool = Field(default=False)
    STATICFILES_IGNORE_PATTERNS: list[Any] = Field(
        default_factory=lambda: [
            "*.py",
            "*.pyc",
            "sass/*.scss",
            "sass/*/*.scss",
            "sass/*/*/*.scss",
            "sass/*/*/*/*.scss",
            "spec",
            "spec_helpers",
            "xmodule_js",
            "common_static",
        ]
    )
    STATICI18N_ROOT: str = Field(default=str(Path("/openedx/edx-platform/cms/static")))
    STATIC_ROOT: str = Field(default=str(Path("/openedx/staticfiles/studio")))
    STATIC_URL: str = Field(default="/static/studio/")
    STUDIO_NAME: Any = Field(
        default=None
    )  # DERIVED: computed from other settings — add a @model_validator to reproduce
    STUDIO_REQUEST_EMAIL: str = Field(default="")
    STUDIO_SHORT_NAME: Any = Field(
        default=None
    )  # DERIVED: computed from other settings — add a @model_validator to reproduce
    SWIFT_USE_TEMP_URLS: bool = Field(default=False)
    TEMPLATES: list[Any] = Field(
        default_factory=lambda: [
            {
                "NAME": "django",
                "BACKEND": "django.template.backends.django.DjangoTemplates",
                "APP_DIRS": False,
                "DIRS": [
                    Path("/openedx/edx-platform/cms/templates"),
                    Path("/openedx/edx-platform/common/templates"),
                    Path(
                        "/openedx/edx-platform/common/djangoapps/pipeline_mako/templates"
                    ),
                    Path("/openedx/edx-platform/common/static"),
                    Path(
                        "/openedx/edx-platform/openedx/core/djangoapps/cors_csrf/templates"
                    ),
                    Path(
                        "/openedx/edx-platform/openedx/core/djangoapps/dark_lang/templates"
                    ),
                    Path("/openedx/edx-platform/openedx/core/lib/license/templates"),
                    Path("/openedx/edx-platform/cms/djangoapps/pipeline_js/templates"),
                ],
                "OPTIONS": {
                    "loaders": [
                        "openedx.core.djangoapps.theming.template_loaders.ThemeTemplateLoader",
                        "common.djangoapps.edxmako.makoloader.MakoFilesystemLoader",
                        "common.djangoapps.edxmako.makoloader.MakoAppDirectoriesLoader",
                    ],
                    "context_processors": [
                        "django.template.context_processors.request",
                        "django.template.context_processors.static",
                        "django.template.context_processors.i18n",
                        "django.contrib.auth.context_processors.auth",
                        "django.template.context_processors.csrf",
                        "django.template.context_processors.media",
                        "django.template.context_processors.tz",
                        "django.contrib.messages.context_processors.messages",
                        "sekizai.context_processors.sekizai",
                        "common.djangoapps.edxmako.shortcuts.marketing_link_context_processor",
                        "lms.djangoapps.courseware.context_processor.user_timezone_locale_prefs",
                        "help_tokens.context_processor",
                        "openedx.core.djangoapps.site_configuration.context_processors.configuration_context",
                        "lms.djangoapps.mobile_api.context_processor.is_from_mobile_app",
                        "openedx.features.survey_report.context_processors.admin_extra_context",
                        "social_django.context_processors.backends",
                        "social_django.context_processors.login_redirect",
                    ],
                    "debug": False,
                },
            },
            {
                "NAME": "mako",
                "BACKEND": "common.djangoapps.edxmako.backend.Mako",
                "APP_DIRS": False,
                "DIRS": [
                    "/openedx/edx-platform/lms/templates",
                    Path("/openedx/edx-platform/common/templates"),
                    Path(
                        "/openedx/edx-platform/common/djangoapps/pipeline_mako/templates"
                    ),
                    Path(
                        "/openedx/edx-platform/openedx/core/djangoapps/cors_csrf/templates"
                    ),
                    Path(
                        "/openedx/edx-platform/openedx/core/djangoapps/dark_lang/templates"
                    ),
                    Path("/openedx/edx-platform/openedx/core/lib/license/templates"),
                    Path("/openedx/edx-platform/lms/djangoapps/teams/templates"),
                    Path(
                        "/openedx/edx-platform/openedx/features/course_experience/templates"
                    ),
                ],
                "OPTIONS": {
                    "context_processors": [
                        "django.template.context_processors.request",
                        "django.template.context_processors.static",
                        "django.template.context_processors.i18n",
                        "django.contrib.auth.context_processors.auth",
                        "django.template.context_processors.csrf",
                        "django.template.context_processors.media",
                        "django.template.context_processors.tz",
                        "django.contrib.messages.context_processors.messages",
                        "sekizai.context_processors.sekizai",
                        "common.djangoapps.edxmako.shortcuts.marketing_link_context_processor",
                        "lms.djangoapps.courseware.context_processor.user_timezone_locale_prefs",
                        "help_tokens.context_processor",
                        "openedx.core.djangoapps.site_configuration.context_processors.configuration_context",
                        "lms.djangoapps.mobile_api.context_processor.is_from_mobile_app",
                        "openedx.features.survey_report.context_processors.admin_extra_context",
                        "social_django.context_processors.backends",
                        "social_django.context_processors.login_redirect",
                    ],
                    "debug": False,
                },
            },
            {
                "NAME": "preview",
                "BACKEND": "common.djangoapps.edxmako.backend.Mako",
                "APP_DIRS": False,
                "DIRS": [
                    "/openedx/edx-platform/lms/templates",
                    Path("/openedx/edx-platform/common/templates"),
                    Path(
                        "/openedx/edx-platform/common/djangoapps/pipeline_mako/templates"
                    ),
                    Path(
                        "/openedx/edx-platform/openedx/core/djangoapps/cors_csrf/templates"
                    ),
                    Path(
                        "/openedx/edx-platform/openedx/core/djangoapps/dark_lang/templates"
                    ),
                    Path("/openedx/edx-platform/openedx/core/lib/license/templates"),
                    Path("/openedx/edx-platform/lms/djangoapps/teams/templates"),
                    Path(
                        "/openedx/edx-platform/openedx/features/course_experience/templates"
                    ),
                ],
                "OPTIONS": {
                    "context_processors": [
                        "django.template.context_processors.request",
                        "django.template.context_processors.static",
                        "django.template.context_processors.i18n",
                        "django.contrib.auth.context_processors.auth",
                        "django.template.context_processors.csrf",
                        "django.template.context_processors.media",
                        "django.template.context_processors.tz",
                        "django.contrib.messages.context_processors.messages",
                        "sekizai.context_processors.sekizai",
                        "common.djangoapps.edxmako.shortcuts.marketing_link_context_processor",
                        "lms.djangoapps.courseware.context_processor.user_timezone_locale_prefs",
                        "help_tokens.context_processor",
                        "openedx.core.djangoapps.site_configuration.context_processors.configuration_context",
                        "lms.djangoapps.mobile_api.context_processor.is_from_mobile_app",
                        "openedx.features.survey_report.context_processors.admin_extra_context",
                        "social_django.context_processors.backends",
                        "social_django.context_processors.login_redirect",
                    ],
                    "debug": False,
                    "namespace": "lms.main",
                },
            },
        ]
    )
    TRANSLATIONS_GITHUB_TOKEN: str = Field(default="")
    TRANSLATIONS_REPO_PATH: str = Field(default="")
    TRANSLATIONS_REPO_URL: str = Field(
        default="https://github.com/mitodl/mitxonline-translations.git"
    )
    UPDATE_SEARCH_INDEX_JOB_QUEUE: str = Field(default="edx.cms.core.default")
    UPLOAD_CHUNK_SIZE_IN_MB: int = Field(default=10)
    USER_TASKS_MAX_AGE: Any = Field(
        default=datetime.timedelta(days=7)
    )  # TODO: refine type
    VIDEO_IMAGE_ASPECT_RATIO: float = Field(default=1.7777777777777777)
    VIDEO_IMAGE_ASPECT_RATIO_ERROR_MARGIN: float = Field(default=0.1)
    VIDEO_IMAGE_ASPECT_RATIO_TEXT: str = Field(default="16:9")
    VIDEO_IMAGE_DEFAULT_FILENAME: str = Field(
        default="images/video-images/default_video_image.png"
    )
    VIDEO_IMAGE_MAX_FILE_SIZE_MB: str = Field(default="2 MB")
    VIDEO_IMAGE_MAX_HEIGHT: int = Field(default=720)
    VIDEO_IMAGE_MAX_WIDTH: int = Field(default=1280)
    VIDEO_IMAGE_MIN_FILE_SIZE_KB: str = Field(default="2 KB")
    VIDEO_IMAGE_MIN_HEIGHT: int = Field(default=360)
    VIDEO_IMAGE_MIN_WIDTH: int = Field(default=640)
    VIDEO_IMAGE_SUPPORTED_FILE_FORMATS: dict[str, Any] = Field(
        default_factory=lambda: {
            ".bmp": "image/bmp",
            ".bmp2": "image/x-ms-bmp",
            ".gif": "image/gif",
            ".jpg": "image/jpeg",
            ".jpeg": "image/jpeg",
            ".png": "image/png",
        }
    )
    VIDEO_TRANSCRIPT_MIGRATIONS_JOB_QUEUE: str = Field(default="edx.cms.core.default")
    VIDEO_UPLOAD_PIPELINE: dict[str, Any] = Field(
        default_factory=lambda: {
            "VEM_S3_BUCKET": "",
            "BUCKET": "",
            "ROOT_PATH": "",
            "CONCURRENT_UPLOAD_LIMIT": 4,
        }
    )
    ZENDESK_API_KEY: str = Field(default="")
    ZENDESK_USER: str = Field(default="")
