FROM nginx:1.31-alpine@sha256:db35bfc6b2951e7f8a72db5db120288c127ffaeeb4a6d4b95a26fead017d5913
# dist/ is pre-exported by `dagger call mfe build-site ... export --path ...`
# into local-dev/tmp-dist/<site-name>/dist/ and the build context is set to
# local-dev/tmp-dist/<site-name>/ so that this COPY picks it up correctly.
COPY dist/ /usr/share/nginx/html
COPY nginx-mfe.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
