FROM nginx:1.31-alpine@sha256:54f2a904c251d5a34adf545a72d32515a15e08418dae0266e23be2e18c66fefa
# dist/ is pre-exported by `dagger call mfe build-site ... export --path ...`
# into local-dev/tmp-dist/<site-name>/dist/ and the build context is set to
# local-dev/tmp-dist/<site-name>/ so that this COPY picks it up correctly.
COPY dist/ /usr/share/nginx/html
COPY nginx-mfe.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
