# This file was generated by django-aqueduct (codegen v2).
# Regenerate with `manage.py generate_aqueduct_settings`.
#
# Code inside `# >>> aqueduct:generated:*` regions is overwritten on every run.
# Add validators and overrides inside `# >>> aqueduct:preserved:*` regions
# (or anywhere outside a generated region) — they survive regeneration.


# >>> aqueduct:generated:imports
from __future__ import annotations

import ast
import datetime
import json
from datetime import timedelta
from typing import Annotated, Any

from corsheaders.defaults import default_headers as corsheaders_default_headers
from django.utils.translation import gettext_lazy as _
from openedx.core.lib.features_setting_proxy import FeaturesProxy
from openedx_content.settings_api import openedx_content_backcompat_apps_to_install
from pydantic import AliasChoices, Field, field_validator
from pydantic_settings import BaseSettings, NoDecode, SettingsConfigDict

# <<< aqueduct:generated:imports


class AqueductSettings(BaseSettings):
    """Typed Django settings model generated by django-aqueduct."""

    model_config = SettingsConfigDict(env_prefix="", extra="allow")

    # >>> aqueduct:generated:fields
    ADVANCED_PROBLEM_TYPES: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: [
            {"component": "drag-and-drop-v2", "boilerplate_name": None},
            {"component": "staffgradedxblock", "boilerplate_name": None},
        ],
        description="Specify XBlocks that should be treated as advanced problems. Each entry is a\ndict:\n'component': the entry-point name of the XBlock.\n'boilerplate_name': an optional YAML template to be used.  Specify as\nNone to omit.",  # noqa: E501
    )
    ALLOW_COURSE_RERUNS: bool = Field(
        default=True,
        description=".. toggle_name: settings.ALLOW_COURSE_RERUNS\n.. toggle_implementation: DjangoSetting\n.. toggle_default: True\n.. toggle_description: This will allow staff member to re-run the course from the studio home page and will\nalways use the split modulestore. When this is set to False, the Re-run Course link will not be available on\nthe studio home page.\n.. toggle_use_cases: open_edx\n.. toggle_creation_date: 2015-02-13\n.. toggle_tickets: https://github.com/openedx/edx-platform/pull/6965",  # noqa: E501
    )
    ALLOW_UNICODE_COURSE_ID: bool = Field(
        default=False,
        description="Allow creating courses with non-ascii characters in the course id",
    )
    ALTERNATE_WORKER_QUEUES: str = Field(default="lms")
    AUTHORING_API_URL: str = Field(default="", description="Misc")
    AWS_SECURITY_TOKEN: str | None = Field(
        default=None
    )  # REDACTED: name looks secret-like — set via a source, not here
    BRANCH_IO_KEY: str = Field(default="")
    BROKER_USE_SSL: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    BUGS_EMAIL: str = Field(default="bugs@example.com")
    BULK_EMAIL_DEFAULT_FROM_EMAIL: str = Field(
        default="no-reply@example.com",
        description="Suffix used to construct 'from' email address for bulk emails.\nA course-specific identifier is prepended.",  # noqa: E501
    )
    BULK_EMAIL_EMAILS_PER_TASK: int = Field(
        default=500,
        description="Parameters for breaking down course enrollment into subtasks.",
    )
    BULK_EMAIL_LOG_SENT_EMAILS: bool = Field(
        default=False,
        description="Flag to indicate if individual email addresses should be logged as they are sent\na bulk email message.",  # noqa: E501
    )
    CELERY_ALWAYS_EAGER: bool = Field(default=False)
    CELERY_QUEUES: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CERT_QUEUE: str = Field(default="certificates")
    CLEAR_REQUEST_CACHE_ON_TASK_COMPLETION: bool = Field(default=True)
    CMS_BASE: Any = Field(
        default=None,
        description="Public domain name of Studio (should be resolvable from the end-user's browser)",  # noqa: E501
    )  # TODO: refine type
    CMS_ROOT: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CMS_ROOT_URL: Any = Field(default=None)  # TODO: refine type
    CMS_SEGMENT_KEY: Any = Field(
        default=None, description="Segment - must explicitly turn it on for production"
    )  # TODO: refine type
    COMMENTS_SERVICE_KEY: str = Field(default="password")
    COMMENTS_SERVICE_URL: str = Field(default="http://localhost:18080")
    CONTACT_EMAIL: str = Field(default="info@example.com")
    CONTACT_MAILING_ADDRESS: Any = Field(
        default_factory=lambda: _("Your Contact Mailing Address Here")
    )  # TODO: refine type
    CORS_ALLOW_HEADERS: Any = Field(
        default_factory=lambda: (
            corsheaders_default_headers
            + (
                "use-jwt-cookie",
                "content-range",
                "content-disposition",
            )
        ),
        description="Set CORS_ALLOW_HEADERS regardless of whether we've enabled ENABLE_CORS_HEADERS\nbecause that decision might happen in a later config file. (The headers to\nallow is an application logic, and not site policy.)",  # noqa: E501
    )  # TODO: refine type
    COURSE_EXPORT_DOWNLOAD_CHUNK_SIZE: int = Field(
        default=8192,
        description="Course exports streamed in blocks of this size. 8192 or 8kb is the default\nsetting for the FileWrapper class used to iterate over the export file data.\nSee: https://docs.python.org/2/library/wsgiref.html#wsgiref.util.FileWrapper",  # noqa: E501
    )
    COURSE_IMPORT_EXPORT_BUCKET: str = Field(default="")
    COURSE_IMPORT_EXPORT_STORAGE: str = Field(
        default="django.core.files.storage.FileSystemStorage", description="Storage"
    )
    COURSE_LIVE_HELP_URL: str = Field(
        default="https://docs.openedx.org/en/latest/educators/how-tos/course_development/add_course_live.html",  # noqa: E501
    )
    COURSE_METADATA_EXPORT_BUCKET: str = Field(default="")
    COURSE_METADATA_EXPORT_STORAGE: str = Field(
        default="django.core.files.storage.FileSystemStorage"
    )
    DEFAULT_AUTO_FIELD: str = Field(default="django.db.models.AutoField")
    DEFAULT_COURSE_LANGUAGE: str = Field(
        default="en", description="Default language for a new course"
    )
    DEFAULT_FEEDBACK_EMAIL: str = Field(default="feedback@example.com")
    DEFAULT_FROM_EMAIL: str = Field(default="registration@example.com")
    DEFAULT_GRADE_DESIGNATIONS: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: ["A", "B", "C", "D"],
        description=".. setting_name: DEFAULT_GRADE_DESIGNATIONS\n.. setting_default: ['A', 'B', 'C', 'D']\n.. setting_description: The default 'pass' grade cutoff designations to be used. The failure grade\nis always 'F' and should not be included in this list.\n.. setting_warning: The DEFAULT_GRADE_DESIGNATIONS list must have more than one designation,\nor else ['A', 'B', 'C', 'D'] will be used as the default grade designations. Also, only the first\n11 grade designations are used by the UI, so it's advisable to restrict the list to 11 items.",  # noqa: E501
    )
    DEFAULT_ORG_LOGO_URL: Any = Field(
        default=None,
        description=".. setting_name: DEFAULT_ORG_LOGO_URL\n.. setting_default: Derived(lambda settings: settings.STATIC_URL + 'images/logo.png')\n.. setting_description: The default logo url for organizations that do not have a logo set.\n.. setting_warning: This url is used as a placeholder for organizations that do not have a logo set.",  # noqa: E501
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    DEFAULT_PRIORITY_QUEUE: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    DEPRECATE_OLD_COURSE_KEYS_IN_STUDIO: bool = Field(
        default=True,
        description=".. toggle_name: settings.DEPRECATE_OLD_COURSE_KEYS_IN_STUDIO\n.. toggle_implementation: DjangoSetting\n.. toggle_default: True\n.. toggle_description: Warn about removing support for deprecated course keys.\nTo enable, set to True.\nTo disable, set to False.\nTo enable with a custom support deadline, set to an ISO-8601 date string:\neg: '2020-09-01'\n.. toggle_use_cases: temporary\n.. toggle_creation_date: 2020-06-12\n.. toggle_target_removal_date: 2021-04-01\n.. toggle_warning: This can be removed once support is removed for deprecated\ncourse keys.\n.. toggle_tickets: https://openedx.atlassian.net/browse/DEPR-58",  # noqa: E501
    )
    DISABLE_ADVANCED_SETTINGS: bool = Field(
        default=False,
        description=".. toggle_name: settings.DISABLE_ADVANCED_SETTINGS\n.. toggle_implementation: DjangoSetting\n.. toggle_default: False\n.. toggle_description: Set to `True` to disable the advanced settings page in Studio for all users except those\nhaving `is_superuser` or `is_staff` set to `True`.\n.. toggle_use_cases: open_edx\n.. toggle_creation_date: 2023-03-31\n.. toggle_tickets: https://github.com/openedx/edx-platform/pull/32015",  # noqa: E501
    )
    DISABLE_COURSE_CREATION: bool = Field(
        default=False,
        description='.. toggle_name: settings.DISABLE_COURSE_CREATION\n.. toggle_implementation: DjangoSetting\n.. toggle_default: False\n.. toggle_description: If set to True, it disables the course creation functionality and hides the "New Course"\nbutton in studio.\nIt is important to note that the value of this flag only affects if the user doesn\'t have a staff role,\notherwise the course creation functionality will work as it should.\n.. toggle_use_cases: open_edx\n.. toggle_creation_date: 2013-12-02\n.. toggle_warning: Another toggle DISABLE_LIBRARY_CREATION overrides DISABLE_COURSE_CREATION, if present.',  # noqa: E501
    )
    DISABLE_DEPRECATED_SIGNIN_URL: bool = Field(
        default=False,
        description=".. toggle_name: DISABLE_DEPRECATED_SIGNIN_URL\n.. toggle_implementation: DjangoSetting\n.. toggle_default: False\n.. toggle_description: Toggle for removing the deprecated /signin url.\n.. toggle_use_cases: temporary\n.. toggle_creation_date: 2019-12-02\n.. toggle_target_removal_date: 2020-06-01\n.. toggle_warning: This url can be removed once it no longer has any real traffic.\n.. toggle_tickets: ARCH-1253",  # noqa: E501
    )
    DISABLE_DEPRECATED_SIGNUP_URL: bool = Field(
        default=False,
        description=".. toggle_name: DISABLE_DEPRECATED_SIGNUP_URL\n.. toggle_implementation: DjangoSetting\n.. toggle_default: False\n.. toggle_description: Toggle for removing the deprecated /signup url.\n.. toggle_use_cases: temporary\n.. toggle_creation_date: 2019-12-02\n.. toggle_target_removal_date: 2020-06-01\n.. toggle_warning: This url can be removed once it no longer has any real traffic.\n.. toggle_tickets: ARCH-1253",  # noqa: E501
    )
    DISCUSSIONS_INCONTEXT_FEEDBACK_URL: str = Field(
        default="",
        description="Feedback link in upgraded discussion notification alert",
    )
    DISCUSSIONS_INCONTEXT_LEARNMORE_URL: str = Field(
        default="https://docs.openedx.org/en/latest/educators/concepts/communication/about_course_discussions.html",  # noqa: E501
        description="Learn More link in upgraded discussion notification alert\npylint: disable=line-too-long",  # noqa: E501
    )
    EDITABLE_SHORT_DESCRIPTION: bool = Field(
        default=True,
        description=".. toggle_name: settings.EDITABLE_SHORT_DESCRIPTION\n.. toggle_implementation: DjangoSetting\n.. toggle_default: True\n.. toggle_description: This feature flag allows editing of short descriptions on the Schedule & Details page in\nOpen edX Studio. Set to False if you want to disable the editing of the course short description.\n.. toggle_use_cases: open_edx\n.. toggle_creation_date: 2014-02-13\n.. toggle_tickets: https://github.com/openedx/edx-platform/pull/2334",  # noqa: E501
    )
    EDXAPP_PARSE_KEYS: Annotated[dict[str, Any], NoDecode] = Field(
        default_factory=lambda: {}
    )
    ELASTIC_FIELD_MAPPINGS: Annotated[dict[str, Any], NoDecode] = Field(
        default_factory=lambda: {"start_date": {"type": "date"}}
    )
    EMAIL_FILE_PATH: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    ENABLE_CONTENT_LIBRARIES: bool = Field(
        default=True,
        description="Enable support for content libraries. Note that content libraries are\nonly supported in courses using split mongo.",  # noqa: E501
    )
    ENABLE_COPPA_COMPLIANCE: bool = Field(
        default=False,
        description=".. toggle_name: ENABLE_COPPA_COMPLIANCE\n.. toggle_implementation: DjangoSetting\n.. toggle_default: False\n.. toggle_description: When True, inforces COPPA compliance and removes YOB field from registration form and accounnt\n.. settings page. Also hide YOB banner from profile page.\n.. toggle_use_cases: open_edx\n.. toggle_creation_date: 2021-10-27\n.. toggle_tickets: 'https://openedx.atlassian.net/browse/VAN-622'",  # noqa: E501
    )
    ENABLE_COUNTRY_ACCESS: bool = Field(default=False)
    ENABLE_COURSEWARE_INDEX: bool = Field(
        default=False, description="Enable the courseware search functionality"
    )
    ENABLE_CREATOR_GROUP: bool = Field(
        default=True,
        description="If set to True, new Studio users won't be able to author courses unless\nan Open edX admin has added them to the course creator group.",  # noqa: E501
    )
    ENABLE_CREDIT_API: bool = Field(default=False)
    ENABLE_DATES_COURSE_APP: bool = Field(
        default=False,
        description=".. toggle_name: ENABLE_DATES_COURSE_APP\n.. toggle_implementation: DjangoSetting\n.. toggle_default: False\n.. toggle_description: Controls whether the Dates course app is surfaced via the course apps API/UI.\n.. toggle_use_cases: open_edx\n.. toggle_creation_date: 2026-02-02\n.. toggle_tickets: https://github.com/openedx/platform-roadmap/issues/392",  # noqa: E501
    )
    ENABLE_DISCUSSION_HOME_PANEL: bool = Field(default=True)
    ENABLE_GRADE_DOWNLOADS: bool = Field(default=True)
    ENABLE_HIDE_FROM_TOC_UI: bool = Field(
        default=False,
        description=".. toggle_name: settings.ENABLE_HIDE_FROM_TOC_UI\n.. toggle_implementation: DjangoSetting\n.. toggle_default: False\n.. toggle_description: When enabled, exposes hide_from_toc xblock attribute so course authors can configure it as\na section visibility option in Studio.\n.. toggle_use_cases: open_edx\n.. toggle_creation_date: 2024-02-29\n.. toggle_tickets: https://github.com/openedx/edx-platform/pull/33952",  # noqa: E501
    )
    ENABLE_JASMINE: bool = Field(default=False)
    ENABLE_LIBRARY_INDEX: bool = Field(
        default=False,
        description="Enable content libraries (modulestore) search functionality",
    )
    ENABLE_LTI_PII_ACKNOWLEDGEMENT: bool = Field(
        default=False,
        description=".. toggle_name: settings.ENABLE_LTI_PII_ACKNOWLEDGEMENT\n.. toggle_implementation: DjangoSetting\n.. toggle_default: False\n.. toggle_description: Enables the lti pii acknowledgement feature for a course\n.. toggle_use_cases: open_edx\n.. toggle_creation_date: 2023-10\n.. toggle_target_removal_date: None\n.. toggle_tickets: 'https://2u-internal.atlassian.net/browse/MST-2055'",  # noqa: E501
    )
    ENABLE_MAX_FAILED_LOGIN_ATTEMPTS: bool = Field(
        default=False,
        description="Turn off account locking if failed login attempts exceeds a limit",
    )
    ENABLE_ORGANIZATION_STAFF_ACCESS_FOR_CONTENT_LIBRARIES: bool = Field(
        default=True,
        description="If set to True, organization staff members can create libraries for their specific\norganization and no other organizations. They do not need to be course creators,\neven when ENABLE_CREATOR_GROUP is True.",  # noqa: E501
    )
    ENABLE_OTHER_COURSE_SETTINGS: bool = Field(
        default=False,
        description='Show a new field in "Advanced settings" that can store custom data about a\ncourse and that can be read from themes',  # noqa: E501
    )
    ENABLE_SEND_XBLOCK_LIFECYCLE_EVENTS_OVER_BUS: bool = Field(
        default=False,
        description=".. toggle_name: settings.ENABLE_SEND_XBLOCK_LIFECYCLE_EVENTS_OVER_BUS\n.. toggle_implementation: DjangoSetting\n.. toggle_default: False\n.. toggle_description: Enables sending xblock lifecycle events over the event bus. Used to create the\nEVENT_BUS_PRODUCER_CONFIG setting\n.. toggle_use_cases: opt_in\n.. toggle_creation_date: 2023-10-10\n.. toggle_target_removal_date: 2023-10-12\n.. toggle_warning: The default may be changed in a later release. See\nhttps://github.com/openedx/openedx-events/issues/265\n.. toggle_tickets: https://github.com/edx/edx-arch-experiments/issues/381",  # noqa: E501
    )
    ENABLE_SEPARATE_ARCHIVED_COURSES: bool = Field(
        default=True,
        description="Whether archived courses (courses with end dates in the past) should be\nshown in Studio in a separate list.",  # noqa: E501
    )
    ENABLE_VIDEO_UPLOAD_PIPELINE: bool = Field(
        default=False,
        description="Turn off Video Upload Pipeline through Studio, by default",
    )
    ENTERPRISE_API_URL: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    ENTERPRISE_CONSENT_API_URL: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    ENTRANCE_EXAMS: bool = Field(
        default=False, description="Toggle course entrance exams feature"
    )
    EXAMS_SERVICE_URL: str = Field(default="http://localhost:18740/api/v1")
    EXAMS_SERVICE_USERNAME: str = Field(default="edx_exams_worker")
    EXTENDED_VIDEO_TRANSCRIPT_LANGUAGES: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: [],
        description="Additional languages that should be supported for video transcripts, not included in ALL_LANGUAGES",  # noqa: E501
    )
    EXTRA_MIDDLEWARE_CLASSES: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: []
    )
    FACEBOOK_API_VERSION: str = Field(default="v2.1")
    FACEBOOK_APP_ID: str = Field(default="FACEBOOK_APP_ID")
    FACEBOOK_APP_SECRET: str | None = Field(
        default=None
    )  # REDACTED: name looks secret-like — set via a source, not here
    FEATURES: Any = Field(
        default_factory=lambda: FeaturesProxy(globals()),
        description="A proxy for feature flags stored in the settings namespace",
    )  # TODO: refine type
    FILES_AND_UPLOAD_TYPE_FILTERS: Annotated[dict[str, Any], NoDecode] = Field(
        default_factory=lambda: {
            "Images": [
                "image/png",
                "image/jpeg",
                "image/jpg",
                "image/gif",
                "image/tiff",
                "image/tif",
                "image/x-icon",
                "image/svg+xml",
                "image/bmp",
                "image/x-ms-bmp",
            ],
            "Documents": [
                "application/pdf",
                "text/plain",
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",  # noqa: E501
                "application/vnd.openxmlformats-officedocument.wordprocessingml.template",  # noqa: E501
                "application/vnd.openxmlformats-officedocument.presentationml.presentation",  # noqa: E501
                "application/vnd.openxmlformats-officedocument.presentationml.slideshow",  # noqa: E501
                "application/vnd.openxmlformats-officedocument.presentationml.template",
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
                "application/msword",
                "application/vnd.ms-excel",
                "application/vnd.ms-powerpoint",
                "application/csv",
                "application/vnd.ms-excel.sheet.macroEnabled.12",
                "text/x-tex",
                "application/x-pdf",
                "application/vnd.ms-excel.sheet.macroenabled.12",
                "file/pdf",
                "image/pdf",
                "text/csv",
                "text/pdf",
                "text/x-sh",
                '"application/pdf"',
            ],
            "Audio": [
                "audio/mpeg",
                "audio/mp3",
                "audio/x-wav",
                "audio/ogg",
                "audio/wav",
                "audio/aac",
                "audio/x-m4a",
                "audio/mp4",
                "audio/x-ms-wma",
            ],
            "Code": [
                "application/json",
                "text/html",
                "text/javascript",
                "application/javascript",
                "text/css",
                "text/x-python",
                "application/x-java-jnlp-file",
                "application/xml",
                "application/postscript",
                "application/x-javascript",
                "application/java-vm",
                "text/x-c++src",
                "text/xml",
                "text/x-scss",
                "application/x-python-code",
                "application/java-archive",
                "text/x-python-script",
                "application/x-ruby",
                "application/mathematica",
                "text/coffeescript",
                "text/x-matlab",
                "application/sql",
                "text/php",
            ],
        },
    )
    FRONTEND_LOGIN_URL: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    FRONTEND_LOGOUT_URL: str = Field(
        default="/logout/",
        description="Warning: Must have trailing slash to activate correct logout view\n(auth_backends, not LMS user_authn)",  # noqa: E501
    )
    FRONTEND_REGISTER_URL: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    GITHUB_PUSH: bool = Field(default=False)
    GITHUB_REPO_ROOT: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    GIT_EXPORT_DEFAULT_IDENT: Annotated[dict[str, Any], NoDecode] = Field(
        default_factory=lambda: {
            "name": "STUDIO_EXPORT_TO_GIT",
            "email": "STUDIO_EXPORT_TO_GIT@example.com",
        },
        description=".. setting_name: GIT_EXPORT_DEFAULT_IDENT\n.. setting_default: {'name': 'STUDIO_EXPORT_TO_GIT', 'email': 'STUDIO_EXPORT_TO_GIT@example.com'}\n.. setting_description: When courses are exported to git, commits are signed with this name/email git identity.",  # noqa: E501
    )
    GIT_REPO_EXPORT_DIR: str = Field(
        default="/edx/var/edxapp/export_course_repos",
        description=".. setting_name: GIT_REPO_EXPORT_DIR\n.. setting_default: '/edx/var/edxapp/export_course_repos'\n.. setting_description: When courses are exported to git, either with the export_git management command or the git\nexport view from the studio (when settings.ENABLE_EXPORT_GIT is True), they are stored in this directory, which\nmust exist at the time of the export.",  # noqa: E501
    )
    GRADES_DOWNLOAD: Annotated[dict[str, Any], NoDecode] = Field(
        default_factory=lambda: {
            "STORAGE_CLASS": "django.core.files.storage.FileSystemStorage",
            "STORAGE_KWARGS": {"location": "/tmp/edx-s3/grades"},
            "STORAGE_TYPE": None,
            "BUCKET": None,
            "ROOT_PATH": None,
        },
        description="These keys are used for all of our asynchronous downloadable files, including\nthe ones that contain information other than grades.",  # noqa: E501
    )
    HIGH_PRIORITY_QUEUE: Any = Field(
        default=None,
        description="Name the exchange and queues w.r.t the SERVICE_VARIANT",
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    HOTJAR_ID: int = Field(default=0)
    INACTIVE_USER_LOGIN: bool = Field(
        default=True,
        description="Social-core setting that allows inactive users to be able to\nlog in. The only case it's used is when user registering a new account through the LMS.",  # noqa: E501
    )
    INACTIVE_USER_URL: Any = Field(
        default=None,
        description="Redirect URL for inactive user. If not set, user will be redirected to /login after the login itself (loop)",  # noqa: E501
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    INSTALLED_APPS: Any = Field(
        default_factory=lambda: [
            # Standard apps
            "django.contrib.auth",
            "django.contrib.contenttypes",
            "django.contrib.humanize",
            "django.contrib.redirects",
            "django.contrib.sessions",
            "django.contrib.sites",
            "django.contrib.messages",
            # Tweaked version of django.contrib.staticfiles
            "openedx.core.djangoapps.staticfiles.apps.EdxPlatformStaticFilesConfig",
            "django_celery_results",
            "method_override",
            # Common Initialization
            "openedx.core.djangoapps.common_initialization.apps.CommonInitializationConfig",
            # Common views
            "openedx.core.djangoapps.common_views",
            # API access administration
            "openedx.core.djangoapps.api_admin",
            # CORS and cross-domain CSRF
            "corsheaders",
            "openedx.core.djangoapps.cors_csrf",
            # Provides the 'django_markup' template library so we can use 'interpolate_html' in django templates  # noqa: E501
            "xss_utils",
            # History tables
            "simple_history",
            # Database-backed configuration
            "config_models",
            "openedx.core.djangoapps.config_model_utils",
            "waffle",
            # Monitor the status of services
            "openedx.core.djangoapps.service_status",
            # Video block configs (This will be moved to Video once it becomes an XBlock)
            "openedx.core.djangoapps.video_config",
            # edX Video Pipeline integration
            "openedx.core.djangoapps.video_pipeline",
            # For CMS
            "cms.djangoapps.contentstore.apps.ContentstoreConfig",
            "common.djangoapps.split_modulestore_django.apps.SplitModulestoreDjangoBackendAppConfig",  # noqa: E501
            "openedx.core.djangoapps.contentserver",
            "cms.djangoapps.course_creators",
            "common.djangoapps.student.apps.StudentConfig",  # misleading name due to sharing with lms  # noqa: E501
            "openedx.core.djangoapps.course_groups",  # not used in cms (yet), but tests run
            "cms.djangoapps.xblock_config.apps.XBlockConfig",
            "cms.djangoapps.export_course_metadata.apps.ExportCourseMetadataConfig",
            "cms.djangoapps.modulestore_migrator",
            # New (openedx_content-based) XBlock runtime
            "openedx.core.djangoapps.xblock.apps.StudioXBlockAppConfig",
            "openedx.core.djangoapps.util.apps.UtilConfig",
            # Tracking
            "common.djangoapps.track",
            "eventtracking.django.apps.EventTrackingConfig",
            # For asset pipelining
            "common.djangoapps.edxmako.apps.EdxMakoConfig",
            "pipeline",
            "common.djangoapps.static_replace",
            "require",
            "webpack_loader",
            # Site configuration for theming and behavioral modification
            "openedx.core.djangoapps.site_configuration",
            # Ability to detect and special-case crawler behavior
            "openedx.core.djangoapps.crawlers",
            # Discussion
            "openedx.core.djangoapps.django_comment_common",
            # Notifications
            "openedx.core.djangoapps.notifications",
            # for course creator table
            "django.contrib.admin",
            # for managing course modes
            "common.djangoapps.course_modes.apps.CourseModesConfig",
            # Verified Track Content Cohorting (Beta feature that will hopefully be removed)
            "openedx.core.djangoapps.verified_track_content",
            # Dark-launching languages
            "openedx.core.djangoapps.dark_lang",
            #
            # User preferences
            "wiki",
            "django_notify",
            "lms.djangoapps.course_wiki",  # Our customizations
            "mptt",
            "sekizai",
            "openedx.core.djangoapps.user_api",
            # Country embargo support
            "openedx.core.djangoapps.embargo",
            # Course action state
            "common.djangoapps.course_action_state",
            "openedx.core.djangoapps.content.course_overviews.apps.CourseOverviewsConfig",
            "openedx.core.djangoapps.content.block_structure.apps.BlockStructureConfig",
            # edx-milestones service
            "milestones",
            # Credit courses
            "openedx.core.djangoapps.credit.apps.CreditConfig",
            "common.djangoapps.xblock_django",
            # Agreements
            "openedx.core.djangoapps.agreements",
            # Catalog integration
            "openedx.core.djangoapps.catalog",
            # Programs support
            "openedx.core.djangoapps.programs.apps.ProgramsConfig",
            # django-oauth-toolkit
            "oauth2_provider",
            # These are apps that aren't strictly needed by Studio, but are imported by
            # other apps that are.  Django 1.8 wants to have imported models supported
            # by installed apps.
            "openedx.core.djangoapps.oauth_dispatch.apps.OAuthDispatchAppConfig",
            "lms.djangoapps.courseware",
            "lms.djangoapps.coursewarehistoryextended",
            "lms.djangoapps.survey.apps.SurveyConfig",
            "lms.djangoapps.verify_student.apps.VerifyStudentConfig",
            "completion",
            # System Wide Roles
            "openedx.core.djangoapps.system_wide_roles",
            # Static i18n support
            "statici18n",
            # Tagging
            "cms.lib.xblock.tagging",
            # Enables default site and redirects
            "django_sites_extensions",
            # additional release utilities to ease automation
            "release_util",
            # rule-based authorization
            "rules.apps.AutodiscoverRulesConfig",
            "bridgekeeper",
            # management of user-triggered async tasks (course import/export, etc.)
            "user_tasks",
            # CMS specific user task handling
            "cms.djangoapps.cms_user_tasks.apps.CmsUserTasksConfig",
            # Unusual migrations
            "common.djangoapps.database_fixups",
            # Customized celery tasks, including persisting failed tasks so they can
            # be retried
            "celery_utils",
            # Waffle related utilities
            "openedx.core.djangoapps.waffle_utils",
            # DRF filters
            "django_filters",
            "cms.djangoapps.api",
            # edx-drf-extensions
            "csrf.apps.CsrfAppConfig",  # Enables frontend apps to retrieve CSRF tokens.
            # Entitlements, used in openedx tests
            "common.djangoapps.entitlements",
            # Asset management for mako templates
            "common.djangoapps.pipeline_mako",
            # API Documentation
            "drf_yasg",
            # Tagging
            "openedx_tagging",
            "openedx.core.djangoapps.content_tagging",
            # Search
            "openedx.core.djangoapps.content.search",
            # For Programs API
            "lms.djangoapps.program_enrollments",
            "openedx.features.course_duration_limits",
            "openedx.features.content_type_gating",
            "openedx.features.discounts",
            "openedx.features.effort_estimation",
            "lms.djangoapps.experiments",
            "openedx.core.djangoapps.external_user_ids",
            # so sample_task is available to celery workers
            "openedx.core.djangoapps.heartbeat",
            # signal handlers to capture course dates into edx-when
            "openedx.core.djangoapps.course_date_signals",
            # Management of per-user schedules
            "openedx.core.djangoapps.schedules",
            "rest_framework_jwt",
            # Learning Sequence Navigation
            "openedx.core.djangoapps.content.learning_sequences.apps.LearningSequencesConfig",
            # Database-backed Organizations App (http://github.com/openedx/edx-organizations)
            "organizations",
            # User and group management via edx-django-utils
            "edx_django_utils.user",
            # Allow Studio to use LMS for SSO
            "social_django",
            # Content Library LTI 1.3 Support.
            "pylti1p3.contrib.django.lti1p3_tool_config",
            # For edx ace template tags
            "edx_ace",
            # alternative swagger generator for CMS API
            "drf_spectacular",
            # Authz
            "openedx.core.djangoapps.authz",
            "openedx_events",
            # Core models to represent courses
            "openedx_catalog",
            # Core apps that power libraries
            "openedx_content",
            *openedx_content_backcompat_apps_to_install(),
        ],
        description="The order of INSTALLED_APPS is important, when adding new apps here\nremember to check that you are not creating new\nRemovedInDjango19Warnings in the test logs.",  # noqa: E501
    )  # TODO: refine type
    IN_CONTEXT_DISCUSSION_ENABLED_DEFAULT: bool = Field(
        default=True,
        description=".. toggle_name: settings.IN_CONTEXT_DISCUSSION_ENABLED_DEFAULT\n.. toggle_implementation: DjangoSetting\n.. toggle_default: True\n.. toggle_description: Set to False to disable in-context discussion for units by default.\n.. toggle_use_cases: open_edx\n.. toggle_creation_date: 2024-09-02",  # noqa: E501
    )
    LEARNER_PORTAL_URL_ROOT: str = Field(
        default="https://learner-portal-localhost:18000"
    )
    LIBRARY_BLOCK_TYPES: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: [
            {"component": "library_content", "boilerplate_name": None}
        ],
    )
    LIBRARY_ENABLED_BLOCKS: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: [
            "problem",
            "video",
            "html",
            "drag-and-drop-v2",
            "openassessment",
            "conditional",
            "done",
            "edx_sga",
            "freetextresponse",
            "google-calendar",
            "google-document",
            "invideoquiz",
            "lti",
            "lti_consumer",
            "pdf",
            "poll",
            "survey",
            "word_cloud",
        ],
        description=".. setting_name: LIBRARY_ENABLED_BLOCKS\n.. setting_default: ['problem', 'video', 'html', 'drag-and-drop-v2']\n.. setting_description: List of block types that are ready/enabled to be created/used\n.. in libraries. Both basic blocks and advanced blocks can be included.\n.. In the future, we will support individual configuration per library - see\n.. openedx/core/djangoapps/content_libraries/api.py::get_allowed_block_types()",  # noqa: E501
    )
    LMS_BASE: Any = Field(default=None)  # TODO: refine type
    LMS_ROOT: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    LOGIN_REDIRECT_URL: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    LOGIN_URL: str = Field(default="/login/")
    LOW_PRIORITY_QUEUE: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    MAINTENANCE_BANNER_TEXT: str = Field(default="Sample banner message")
    MARKETING_EMAILS_OPT_IN: bool = Field(default=False)
    MAX_ASSET_UPLOAD_FILE_SIZE_IN_MB: int = Field(
        default=20, description="Max size of asset uploads to GridFS"
    )
    MAX_ASSET_UPLOAD_FILE_SIZE_URL: str = Field(
        default="",
        description="FAQ url to direct users to if they upload\na file that exceeds the above size",  # noqa: E501
    )
    MAX_BLOCKS_PER_CONTENT_LIBRARY: int = Field(default=100000)
    MAX_FAILED_LOGIN_ATTEMPTS_ALLOWED: int = Field(default=6)
    MAX_FAILED_LOGIN_ATTEMPTS_LOCKOUT_PERIOD_SECS: Any = Field(
        default_factory=lambda: 30 * 60
    )  # TODO: refine type
    MEILISEARCH_API_KEY: str | None = Field(
        default=None
    )  # REDACTED: name looks secret-like — set via a source, not here
    MEILISEARCH_ENABLED: bool = Field(
        default=False,
        description="Enable Studio search features (powered by Meilisearch) (beta, off by default)",  # noqa: E501
    )
    MEILISEARCH_INDEX_PREFIX: str = Field(
        default="",
        description='To support multi-tenancy, you can prefix all indexes with a common key like "sandbox7-"\nand use a restricted tenant token in place of an API key, so that this Open edX instance\ncan only use the index(es) that start with this prefix.\nSee https://www.meilisearch.com/docs/learn/security/tenant_tokens',  # noqa: E501
    )
    MEILISEARCH_PUBLIC_URL: str = Field(
        default="http://meilisearch.example.com",
        description="URL that browsers (end users) can use to reach Meilisearch. Should be HTTPS in production.",  # noqa: E501
    )
    MEILISEARCH_URL: str = Field(
        default="http://meilisearch",
        description="Meilisearch URL that the python backend can use. Often points to another docker container or k8s service.",  # noqa: E501
    )
    MIDDLEWARE: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: [
            "openedx.core.lib.x_forwarded_for.middleware.XForwardedForMiddleware",
            "edx_django_utils.security.csp.middleware.content_security_policy_middleware",  # noqa: E501
            "crum.CurrentRequestUserMiddleware",
            "edx_django_utils.cache.middleware.RequestCacheMiddleware",
            "edx_django_utils.monitoring.CookieMonitoringMiddleware",
            "edx_django_utils.monitoring.DeploymentMonitoringMiddleware",
            "edx_django_utils.monitoring.FrontendMonitoringMiddleware",
            "edx_django_utils.monitoring.MonitoringMemoryMiddleware",
            "openedx.core.djangoapps.header_control.middleware.HeaderControlMiddleware",
            "django.middleware.cache.UpdateCacheMiddleware",
            "django.middleware.common.CommonMiddleware",
            "django.contrib.sites.middleware.CurrentSiteMiddleware",
            "django.middleware.csrf.CsrfViewMiddleware",
            "corsheaders.middleware.CorsMiddleware",
            "openedx.core.djangoapps.cors_csrf.middleware.CorsCSRFMiddleware",
            "openedx.core.djangoapps.cors_csrf.middleware.CsrfCrossDomainCookieMiddleware",  # noqa: E501
            "edx_rest_framework_extensions.auth.jwt.middleware.JwtAuthCookieMiddleware",
            "django_sites_extensions.middleware.RedirectMiddleware",
            "openedx.core.djangoapps.safe_sessions.middleware.SafeSessionMiddleware",
            "method_override.middleware.MethodOverrideMiddleware",
            "openedx.core.djangoapps.cache_toolbox.middleware.CacheBackedAuthenticationMiddleware",  # noqa: E501
            "common.djangoapps.student.middleware.UserStandingMiddleware",
            "django.contrib.messages.middleware.MessageMiddleware",
            "common.djangoapps.track.middleware.TrackMiddleware",
            "openedx.core.djangoapps.lang_pref.middleware.LanguagePreferenceMiddleware",
            "openedx.core.djangoapps.dark_lang.middleware.DarkLangMiddleware",
            "openedx.core.djangoapps.embargo.middleware.EmbargoMiddleware",
            "django.middleware.locale.LocaleMiddleware",
            "codejail.django_integration.ConfigureCodeJailMiddleware",
            "openedx.core.djangoapps.session_inactivity_timeout.middleware.SessionInactivityTimeout",  # noqa: E501
            "openedx.core.djangoapps.theming.middleware.CurrentSiteThemeMiddleware",
            "django.middleware.clickjacking.XFrameOptionsMiddleware",
            "waffle.middleware.WaffleMiddleware",
            "edx_django_utils.cache.middleware.TieredCacheMiddleware",
            "edx_rest_framework_extensions.middleware.RequestCustomAttributesMiddleware",  # noqa: E501
            "edx_rest_framework_extensions.auth.jwt.middleware.EnsureJWTAuthSettingsMiddleware",  # noqa: E501
            "simple_history.middleware.HistoryRequestMiddleware",
            "openedx.core.djangoapps.site_configuration.middleware.SessionCookieDomainOverrideMiddleware",  # noqa: E501
        ],
    )
    MODULESTORE_BRANCH: str = Field(default="draft-preferred")
    OAUTH_ID_TOKEN_EXPIRATION: str | None = Field(
        default=None,
        description="5 minute expiration time for JWT id tokens issued for external API requests.",  # noqa: E501
    )  # REDACTED: name looks secret-like — set via a source, not here
    OPTIONAL_FIELD_API_RATELIMIT: str = Field(default="10/h")
    ORA2_FILE_PREFIX: str = Field(
        default="default_env-default_deployment/ora2",
        description="By default, don't use a file prefix",
    )
    ORGANIZATIONS_AUTOCREATE: bool = Field(
        default=True,
        description='.. toggle_name: ORGANIZATIONS_AUTOCREATE\n.. toggle_implementation: DjangoSetting\n.. toggle_default: True\n.. toggle_description: When enabled, creating a course run or content library with\nan "org slug" that does not map to an Organization in the database will trigger the\ncreation of a new Organization, with its name and short_name set to said org slug.\nWhen disabled, creation of such content with an unknown org slug will instead\nresult in a validation error.\nIf you want the Organization table to be an authoritative information source in\nStudio, then disable this; however, if you want the table to just be a reflection of\nthe orgs referenced in Studio content, then leave it enabled.\n.. toggle_use_cases: open_edx\n.. toggle_creation_date: 2020-11-02\n.. toggle_tickets: https://github.com/openedx/edx-organizations/blob/master/docs/decisions/0001-phase-in-db-backed-organizations-to-all.rst',  # noqa: E501
    )
    PARSE_KEYS: Annotated[dict[str, Any], NoDecode] = Field(default_factory=lambda: {})
    PAYMENT_SUPPORT_EMAIL: str = Field(default="billing@example.com")
    PRESS_EMAIL: str = Field(default="press@example.com")
    PREVENT_CONCURRENT_LOGINS: bool = Field(
        default=False, description="Prevent concurrent logins per user"
    )
    PROCTORING_SETTINGS: Annotated[dict[str, Any], NoDecode] = Field(
        default_factory=lambda: {}
    )
    PROJECT_ROOT: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    REQUIRE_JS: str = Field(
        default="js/vendor/requiresjs/require.js",
        description="The name of the require.js script used by your project, relative to REQUIRE_BASE_URL.",  # noqa: E501
    )
    RETIRED_EMAIL_FMT: Any = Field(
        default=None, description="See annotations in lms/envs/common.py for details."
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    RETIRED_USERNAME_FMT: Any = Field(
        default=None, description="See annotations in lms/envs/common.py for details."
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    RETIRED_USER_SALTS: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: ["abc", "123"],
        description="See annotations in lms/envs/common.py for details.",
    )
    RETIREMENT_SERVICE_WORKER_USERNAME: str = Field(
        default="RETIREMENT_SERVICE_USER",
        description="See annotations in lms/envs/common.py for details.",
    )
    SCRAPE_YOUTUBE_THUMBNAILS_JOB_QUEUE: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    SECRET_KEY: str | None = Field(
        default=None, description="Dummy secret key for dev/test"
    )  # REDACTED: name looks secret-like — set via a source, not here
    SERVER_EMAIL: str = Field(default="devops@example.com")
    SERVICE_VARIANT: str = Field(default="cms")
    SOCIAL_AUTH_STRATEGY: str = Field(
        default="auth_backends.strategies.EdxDjangoStrategy",
        description="Use LMS SSO for login, once enabled by setting LOGIN_URL (see docs/guides/studio_oauth.rst)",  # noqa: E501
    )
    SQUELCH_PII_IN_LOGS: bool = Field(
        default=False,
        description="Hide any Personally Identifiable Information from application logs",  # noqa: E501
    )
    STATIC_ROOT: str | None = Field(
        default=None, validation_alias=AliasChoices("STATIC_ROOT_CMS")
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    STATIC_URL: str = Field(default="/static/studio/", description="Static content")
    STUDIO_NAME: Any = Field(
        default_factory=lambda: _("Your Platform Studio")
    )  # TODO: refine type
    STUDIO_REQUEST_EMAIL: str = Field(
        default="",
        description="email address for studio staff (eg to request course creation)",
    )
    STUDIO_SHORT_NAME: Any = Field(
        default_factory=lambda: _("Studio")
    )  # TODO: refine type
    SWIFT_USE_TEMP_URLS: bool = Field(default=False)
    TECH_SUPPORT_EMAIL: str = Field(default="technical@example.com")
    UNIVERSITY_EMAIL: str = Field(default="university@example.com")
    UPDATE_SEARCH_INDEX_JOB_QUEUE: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    UPLOAD_CHUNK_SIZE_IN_MB: int = Field(
        default=10,
        description="Size of chunks into which asset uploads will be divided",
    )
    USER_TASKS_MAX_AGE: datetime.timedelta = Field(
        default_factory=lambda: timedelta(days=7),
        description="How long until database records about the outcome of a task and its artifacts get deleted?",  # noqa: E501
    )
    VIDEO_IMAGE_ASPECT_RATIO: Any = Field(
        default_factory=lambda: 16 / 9.0
    )  # TODO: refine type
    VIDEO_IMAGE_ASPECT_RATIO_ERROR_MARGIN: float = Field(default=0.1)
    VIDEO_IMAGE_ASPECT_RATIO_TEXT: str = Field(default="16:9")
    VIDEO_IMAGE_DEFAULT_FILENAME: str = Field(
        default="images/video-images/default_video_image.png"
    )
    VIDEO_IMAGE_MAX_AGE: int = Field(default=31536000)
    VIDEO_IMAGE_MAX_FILE_SIZE_MB: str = Field(default="2 MB")
    VIDEO_IMAGE_MAX_HEIGHT: int = Field(default=720)
    VIDEO_IMAGE_MAX_WIDTH: int = Field(default=1280)
    VIDEO_IMAGE_MIN_FILE_SIZE_KB: str = Field(default="2 KB")
    VIDEO_IMAGE_MIN_HEIGHT: int = Field(default=360)
    VIDEO_IMAGE_MIN_WIDTH: int = Field(default=640)
    VIDEO_IMAGE_SETTINGS: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    VIDEO_IMAGE_SUPPORTED_FILE_FORMATS: Annotated[dict[str, Any], NoDecode] = Field(
        default_factory=lambda: {
            ".bmp": "image/bmp",
            ".bmp2": "image/x-ms-bmp",
            ".gif": "image/gif",
            ".jpg": "image/jpeg",
            ".jpeg": "image/jpeg",
            ".png": "image/png",
        },
    )
    VIDEO_TRANSCRIPT_MIGRATIONS_JOB_QUEUE: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    XBLOCK_FS_STORAGE_BUCKET: Any = Field(default=None)  # TODO: refine type
    XBLOCK_FS_STORAGE_PREFIX: Any = Field(default=None)  # TODO: refine type
    XBLOCK_MIXINS: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    ZENDESK_API_KEY: str | None = Field(
        default=None
    )  # REDACTED: name looks secret-like — set via a source, not here
    ZENDESK_USER: str = Field(default="")
    # <<< aqueduct:generated:fields

    # >>> aqueduct:generated:container_decoders
    @field_validator(
        "ADVANCED_PROBLEM_TYPES",
        "DEFAULT_GRADE_DESIGNATIONS",
        "EXTENDED_VIDEO_TRANSCRIPT_LANGUAGES",
        "EXTRA_MIDDLEWARE_CLASSES",
        "LIBRARY_BLOCK_TYPES",
        "LIBRARY_ENABLED_BLOCKS",
        "MIDDLEWARE",
        "RETIRED_USER_SALTS",
        mode="before",
    )
    @classmethod
    def _aqueduct_decode_list_fields(cls, value: object) -> object:
        """Parse a list from a JSON, Python-literal, or comma-separated env string."""
        if not isinstance(value, str):
            return value
        try:
            parsed = json.loads(value)
        except (ValueError, TypeError):
            try:
                parsed = ast.literal_eval(value)
            except (ValueError, SyntaxError):
                parsed = None
        if isinstance(parsed, list):
            return parsed
        stripped = value.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            stripped = stripped[1:-1].strip()
        if not stripped:
            return []
        return [item.strip() for item in stripped.split(",")]

    @field_validator(
        "EDXAPP_PARSE_KEYS",
        "ELASTIC_FIELD_MAPPINGS",
        "FILES_AND_UPLOAD_TYPE_FILTERS",
        "GIT_EXPORT_DEFAULT_IDENT",
        "GRADES_DOWNLOAD",
        "PARSE_KEYS",
        "PROCTORING_SETTINGS",
        "VIDEO_IMAGE_SUPPORTED_FILE_FORMATS",
        mode="before",
    )
    @classmethod
    def _aqueduct_decode_dict_fields(cls, value: object) -> object:
        """Parse a dict from a JSON or Python-literal env string."""
        if not isinstance(value, str):
            return value
        try:
            parsed = json.loads(value)
        except (ValueError, TypeError):
            parsed = None
        if isinstance(parsed, dict):
            return parsed
        return ast.literal_eval(value)

    # <<< aqueduct:generated:container_decoders

    # >>> aqueduct:preserved:validators
    # Add @model_validator / @field_validator methods here.
    # This region is preserved across regeneration.
    # <<< aqueduct:preserved:validators
