# This file was generated by django-aqueduct.
# Run `dagger call platform regenerate-aqueduct-settings ...` to regenerate.
#
# For the generic Open edX deployment (no custom packages), this model
# adds no service-specific fields beyond the shared base.

from __future__ import annotations

from .base import SharedAqueductSettings


class AqueductSettings(SharedAqueductSettings):
    """Typed CMS Django settings model — generic Open edX deployment.

    No CMS-specific or custom-plugin settings beyond the shared base.
    After adding custom pip packages, regenerate this file with::

        dagger call platform regenerate-aqueduct-settings \\
          --deployment-name generic \\
          --pip-package-lists ./deployments/generic/pip_package_lists \\
          --pip-package-overrides ./deployments/generic/pip_package_overrides \\
          export --path ./generated

        cp generated/cms/models/aqueduct.py \\
           deployments/generic/settings/cms/models/aqueduct.py
    """
